// Fashion & Textile Products

import { Product } from './types'

export const fashionTextileProducts: Product[] = [
    {
        slug: "scarf",
        name: "Custom Printed Scarves",
        sectionId: "fashion-textile",
        price: "Starting from $25",
        rating: 4.8,
        reviews: 156,
        images: ["/products/29 Bags/scarf_printing_dubai_01.jpg", "/products/29 Bags/scarf_printing_dubai_02.jpg"],
        description: "Premium quality scarves with custom prints for fashion and branding.",
        features: ["High-quality fabric", "Custom designs", "Various sizes"],
        specifications: { Material: "Silk / Polyester", Size: "Various options", Printing: "Digital" },
        variations: [
            { name: "Silk Scarf", price: "$35", image: "/images/scarf-silk.png" },
            { name: "Polyester Scarf", price: "$25", image: "/images/scarf-polyester.png" },
        ],
        faqs: [
            { question: "What fabrics are available?", answer: "Silk, polyester, and cotton blends available." },
            { question: "Can I get custom sizes?", answer: "Yes, we can create scarves in various dimensions." },
        ],
    },
    {
        slug: "sheila",
        name: "Traditional Sheila",
        sectionId: "fashion-textile",
        price: "Starting from $30",
        rating: 4.7,
        reviews: 89,
        images: ["/products/29 Bags/sheila_printing_dubai_01.jpg", "/products/29 Bags/sheila_printing_dubai_02.jpg"],
        description: "Traditional sheila with modern custom printing options.",
        features: ["Traditional design", "Custom colors", "Premium materials"],
        specifications: { Material: "Cotton blend", Size: "Standard", Printing: "Screen print" },
        variations: [
            { name: "Standard Sheila", price: "$30", image: "/images/sheila-standard.png" },
            { name: "Premium Sheila", price: "$45", image: "/images/sheila-premium.png" },
        ],
        faqs: [
            { question: "What colors are available?", answer: "Various traditional and custom colors available." },
            { question: "Is it suitable for daily wear?", answer: "Yes, designed for comfort and durability." },
        ],
    },
    {
        slug: "bandana",
        name: "Custom Bandanas",
        sectionId: "fashion-textile",
        price: "Starting from $15",
        rating: 4.6,
        reviews: 234,
        images: ["/products/29 Bags/bandana_printing_dubai_01.jpg", "/products/29 Bags/bandana_printing_dubai_02.jpg"],
        description: "Versatile custom bandanas for fashion, sports, and promotional use.",
        features: ["100% cotton", "Various patterns", "Custom printing"],
        specifications: { Material: "Cotton", Size: "Standard", Printing: "Screen print" },
        variations: [
            { name: "Cotton Bandana", price: "$15", image: "/images/bandana-cotton.png" },
            { name: "Premium Bandana", price: "$25", image: "/images/bandana-premium.png" },
        ],
        faqs: [
            { question: "What sizes are available?", answer: "Standard bandana size plus custom dimensions." },
            { question: "Can I get custom patterns?", answer: "Yes, we can create custom patterns and designs." },
        ],
    },
    {
        slug: "hair-scarf",
        name: "Hair Scarves",
        sectionId: "fashion-textile",
        price: "Starting from $20",
        rating: 4.5,
        reviews: 67,
        images: ["/products/29 Bags/hair_scarf_printing_dubai_01.jpg", "/products/29 Bags/hair_scarf_printing_dubai_02.jpg"],
        description: "Elegant hair scarves for fashion and functionality.",
        features: ["Soft fabric", "Various styles", "Custom designs"],
        specifications: { Material: "Silk / Satin", Size: "Various", Style: "Custom options" },
        variations: [
            { name: "Silk Hair Scarf", price: "$30", image: "/images/hair-scarf-silk.png" },
            { name: "Satin Hair Scarf", price: "$20", image: "/images/hair-scarf-satin.png" },
        ],
        faqs: [
            { question: "What styles are available?", answer: "Various styles including headbands, wraps, and ties." },
            { question: "Is it suitable for all hair types?", answer: "Yes, designed to work with all hair types." },
        ],
    },
    {
        slug: "bag-scarf",
        name: "Bag Scarves",
        sectionId: "fashion-textile",
        price: "Starting from $18",
        rating: 4.4,
        reviews: 45,
        images: ["/products/29 Bags/bag_scarf_printing_dubai_01.jpg", "/products/29 Bags/bag_scarf_printing_dubai_02.jpg"],
        description: "Stylish bag scarves to accessorize and protect your bags.",
        features: ["Protective function", "Fashion accessory", "Custom designs"],
        specifications: { Material: "Cotton / Polyester", Size: "Various", Function: "Protection & Style" },
        variations: [
            { name: "Cotton Bag Scarf", price: "$18", image: "/images/bag-scarf-cotton.png" },
            { name: "Premium Bag Scarf", price: "$28", image: "/images/bag-scarf-premium.png" },
        ],
        faqs: [
            { question: "What sizes are available?", answer: "Various sizes to fit different bag types." },
            { question: "Can I get custom logos?", answer: "Yes, we can add your custom logo or design." },
        ],
    },
    {
        slug: "abaya",
        name: "Custom Abayas",
        sectionId: "fashion-textile",
        price: "Starting from $85",
        rating: 4.9,
        reviews: 123,
        images: ["/images/abaya1.png", "/images/abaya2.png"],
        description: "Elegant custom abayas with modern designs and premium materials.",
        features: ["Premium materials", "Custom designs", "Various styles"],
        specifications: { Material: "Premium fabric", Size: "Custom sizing", Style: "Traditional & Modern" },
        variations: [
            { name: "Standard Abaya", price: "$85", image: "/images/abaya-standard.png" },
            { name: "Premium Abaya", price: "$125", image: "/images/abaya-premium.png" },
        ],
        faqs: [
            { question: "Do you offer custom sizing?", answer: "Yes, we provide custom sizing for all abayas." },
            { question: "What materials are available?", answer: "Various premium fabrics including chiffon, crepe, and jersey." },
        ],
    },
    {
        slug: "sarong",
        name: "Custom Sarongs",
        sectionId: "fashion-textile",
        price: "Starting from $35",
        rating: 4.6,
        reviews: 78,
        images: ["/images/sarong1.png", "/images/sarong2.png"],
        description: "Versatile sarongs for beach, casual wear, and home decoration.",
        features: ["Lightweight fabric", "Quick-drying", "Custom designs"],
        specifications: { Material: "Cotton / Rayon", Size: "Standard", Usage: "Multi-purpose" },
        variations: [
            { name: "Cotton Sarong", price: "$35", image: "/images/sarong-cotton.png" },
            { name: "Rayon Sarong", price: "$45", image: "/images/sarong-rayon.png" },
        ],
        faqs: [
            { question: "What sizes are available?", answer: "Standard sarong size plus custom dimensions." },
            { question: "Is it suitable for beach use?", answer: "Yes, lightweight and quick-drying for beach activities." },
        ],
    },
    {
        slug: "beach-shorts",
        name: "Custom Beach Shorts",
        sectionId: "fashion-textile",
        price: "Starting from $25",
        rating: 4.5,
        reviews: 56,
        images: ["/images/beach-shorts1.png", "/images/beach-shorts2.png"],
        description: "Comfortable beach shorts with custom prints and designs.",
        features: ["Quick-drying fabric", "Custom designs", "Various sizes"],
        specifications: { Material: "Polyester blend", Size: "S-XXL", Features: "Quick-dry" },
        variations: [
            { name: "Standard Beach Shorts", price: "$25", image: "/images/beach-shorts-standard.png" },
            { name: "Premium Beach Shorts", price: "$35", image: "/images/beach-shorts-premium.png" },
        ],
        faqs: [
            { question: "What sizes are available?", answer: "Sizes from S to XXL available." },
            { question: "Are they suitable for swimming?", answer: "Yes, quick-drying material suitable for water activities." },
        ],
    },
    {
        slug: "pocket-handkerchief",
        name: "Pocket Handkerchiefs",
        sectionId: "fashion-textile",
        price: "Starting from $12",
        rating: 4.4,
        reviews: 34,
        images: ["/images/pocket-handkerchief1.png", "/images/pocket-handkerchief2.png"],
        description: "Elegant pocket handkerchiefs for formal and casual use.",
        features: ["Premium materials", "Custom designs", "Various colors"],
        specifications: { Material: "Cotton / Silk", Size: "Standard", Style: "Formal & Casual" },
        variations: [
            { name: "Cotton Handkerchief", price: "$12", image: "/images/handkerchief-cotton.png" },
            { name: "Silk Handkerchief", price: "$25", image: "/images/handkerchief-silk.png" },
        ],
        faqs: [
            { question: "What materials are available?", answer: "Cotton and silk options available." },
            { question: "Can I get custom embroidery?", answer: "Yes, we offer custom embroidery services." },
        ],
    },
    {
        slug: "woven-fabric-labels",
        name: "Woven Fabric Labels",
        sectionId: "fashion-textile",
        price: "Starting from $8",
        rating: 4.3,
        reviews: 89,
        images: ["/images/woven-labels1.png", "/images/woven-labels2.png"],
        description: "Professional woven fabric labels for clothing and textile products.",
        features: ["High-quality weaving", "Custom designs", "Various sizes"],
        specifications: { Material: "Cotton / Polyester", Size: "Custom", Weaving: "Professional" },
        variations: [
            { name: "Cotton Woven Label", price: "$8", image: "/images/woven-label-cotton.png" },
            { name: "Premium Woven Label", price: "$15", image: "/images/woven-label-premium.png" },
        ],
        faqs: [
            { question: "What's the minimum order quantity?", answer: "Minimum 100 pieces per order." },
            { question: "Can I get custom colors?", answer: "Yes, we can match any color for your labels." },
        ],
    },
    {
        slug: "scrunchie",
        name: "Custom Scrunchies",
        sectionId: "fashion-textile",
        price: "Starting from $5",
        rating: 4.7,
        reviews: 167,
        images: ["/images/scrunchie1.png", "/images/scrunchie2.png"],
        description: "Trendy custom scrunchies for hair styling and fashion accessories.",
        features: ["Soft fabric", "Various colors", "Custom designs"],
        specifications: { Material: "Satin / Velvet", Size: "Standard", Style: "Various" },
        variations: [
            { name: "Satin Scrunchie", price: "$5", image: "/images/scrunchie-satin.png" },
            { name: "Velvet Scrunchie", price: "$8", image: "/images/scrunchie-velvet.png" },
        ],
        faqs: [
            { question: "What fabrics are available?", answer: "Satin, velvet, and cotton options available." },
            { question: "Can I get bulk discounts?", answer: "Yes, discounts available for orders over 50 pieces." },
        ],
    },
    // --- MISSING FASHION & TEXTILE PRODUCTS ---
    // Soft Furnishing
    {
        slug: "decorative-pillows",
        name: "Decorative Pillows",
        sectionId: "fashion-textile",
        price: "Starting from $25",
        rating: 4.6,
        reviews: 89,
        images: ["/images/decorative-pillows1.png", "/images/decorative-pillows2.png"],
        description: "Beautiful decorative pillows for home and office decoration.",
        features: ["Custom designs", "Premium fabrics", "Various sizes"],
        specifications: { Material: "Cotton/Silk", Size: "Various", Design: "Custom" },
        variations: [
            { name: "Cotton Decorative Pillow", price: "$25", image: "/images/cotton-pillow.png" },
            { name: "Silk Decorative Pillow", price: "$45", image: "/images/silk-pillow.png" },
        ],
        faqs: [
            { question: "What fabrics are available?", answer: "Cotton, silk, velvet, and various premium fabrics." },
            { question: "Can I get custom designs?", answer: "Yes, we can create custom pillow designs and patterns." },
        ],
    },
    {
        slug: "floor-cushion",
        name: "Floor Cushions",
        sectionId: "fashion-textile",
        price: "Starting from $30",
        rating: 4.5,
        reviews: 67,
        images: ["/images/floor-cushion1.png", "/images/floor-cushion2.png"],
        description: "Comfortable floor cushions for seating and decoration.",
        features: ["Comfortable seating", "Custom designs", "Durable materials"],
        specifications: { Material: "Fabric", Filling: "Foam", Size: "Large" },
        variations: [
            { name: "Standard Floor Cushion", price: "$30", image: "/images/floor-cushion-standard.png" },
            { name: "Premium Floor Cushion", price: "$50", image: "/images/floor-cushion-premium.png" },
        ],
        faqs: [
            { question: "What filling is used?", answer: "High-quality foam filling for comfort and durability." },
            { question: "Are they easy to clean?", answer: "Yes, removable covers make cleaning easy." },
        ],
    },
    {
        slug: "tiny-cushion",
        name: "Tiny Cushions",
        sectionId: "fashion-textile",
        price: "Starting from $8",
        rating: 4.4,
        reviews: 45,
        images: ["/images/tiny-cushion1.png", "/images/tiny-cushion2.png"],
        description: "Small decorative cushions for accent decoration.",
        features: ["Compact size", "Decorative purpose", "Custom designs"],
        specifications: { Material: "Fabric", Size: "Small", Purpose: "Decorative" },
        variations: [
            { name: "Mini Cushion", price: "$8", image: "/images/mini-cushion.png" },
            { name: "Accent Cushion", price: "$12", image: "/images/accent-cushion.png" },
        ],
        faqs: [
            { question: "What sizes are available?", answer: "Various small sizes from 4x4 inches to 8x8 inches." },
            { question: "Can I get custom embroidery?", answer: "Yes, we can add custom embroidery to tiny cushions." },
        ],
    },
    {
        slug: "bolster-pillow",
        name: "Bolster Pillows",
        sectionId: "fashion-textile",
        price: "Starting from $35",
        rating: 4.7,
        reviews: 78,
        images: ["/images/bolster-pillow1.png", "/images/bolster-pillow2.png"],
        description: "Long bolster pillows for decorative and functional use.",
        features: ["Long cylindrical shape", "Decorative ends", "Premium materials"],
        specifications: { Shape: "Cylindrical", Material: "Premium fabric", Ends: "Decorative" },
        variations: [
            { name: "Standard Bolster", price: "$35", image: "/images/bolster-standard.png" },
            { name: "Premium Bolster", price: "$55", image: "/images/bolster-premium.png" },
        ],
        faqs: [
            { question: "What are the typical dimensions?", answer: "Standard size is 24 inches long with 6-8 inch diameter." },
            { question: "Can I get custom lengths?", answer: "Yes, we can create bolster pillows in custom lengths." },
        ],
    },
    {
        slug: "bean-bags",
        name: "Bean Bags",
        sectionId: "fashion-textile",
        price: "Starting from $45",
        rating: 4.8,
        reviews: 134,
        images: ["/images/bean-bags1.png", "/images/bean-bags2.png"],
        description: "Comfortable bean bags for casual seating.",
        features: ["Comfortable seating", "Various sizes", "Durable covers"],
        specifications: { Filling: "Bean/Polystyrene", Cover: "Removable", Size: "Various" },
        variations: [
            { name: "Kids Bean Bag", price: "$45", image: "/images/kids-bean-bag.png" },
            { name: "Adult Bean Bag", price: "$65", image: "/images/adult-bean-bag.png" },
        ],
        faqs: [
            { question: "What filling is used?", answer: "High-quality polystyrene beads for comfort and support." },
            { question: "Are the covers washable?", answer: "Yes, removable covers are machine washable." },
        ],
    },
    {
        slug: "blanket",
        name: "Custom Blankets",
        sectionId: "fashion-textile",
        price: "Starting from $40",
        rating: 4.9,
        reviews: 156,
        images: ["/images/blanket1.png", "/images/blanket2.png"],
        description: "Soft and warm custom blankets for comfort and decoration.",
        features: ["Soft materials", "Custom designs", "Various sizes"],
        specifications: { Material: "Fleece/Cotton", Size: "Various", Design: "Custom" },
        variations: [
            { name: "Fleece Blanket", price: "$40", image: "/images/fleece-blanket.png" },
            { name: "Cotton Blanket", price: "$55", image: "/images/cotton-blanket.png" },
        ],
        faqs: [
            { question: "What materials are available?", answer: "Fleece, cotton, wool, and various premium materials." },
            { question: "Can I get personalized designs?", answer: "Yes, we can add personal names, logos, or custom designs." },
        ],
    },
    {
        slug: "fabric-wrap",
        name: "Fabric Wraps",
        sectionId: "fashion-textile",
        price: "Starting from $20",
        rating: 4.5,
        reviews: 67,
        images: ["/images/fabric-wrap1.png", "/images/fabric-wrap2.png"],
        description: "Versatile fabric wraps for fashion and decoration.",
        features: ["Versatile use", "Premium fabrics", "Custom designs"],
        specifications: { Material: "Premium fabric", Size: "Large", Use: "Multi-purpose" },
        variations: [
            { name: "Standard Fabric Wrap", price: "$20", image: "/images/fabric-wrap-standard.png" },
            { name: "Premium Fabric Wrap", price: "$35", image: "/images/fabric-wrap-premium.png" },
        ],
        faqs: [
            { question: "How can fabric wraps be used?", answer: "As shawls, scarves, table runners, or decorative elements." },
            { question: "What sizes are available?", answer: "Various sizes from 60x60 inches to 90x90 inches." },
        ],
    },
    // Pouches
    {
        slug: "velvet-pouches",
        name: "Velvet Pouches",
        sectionId: "fashion-textile",
        price: "Starting from $8",
        rating: 4.6,
        reviews: 89,
        images: ["/images/velvet-pouches1.png", "/images/velvet-pouches2.png"],
        description: "Luxurious velvet pouches for jewelry and small items.",
        features: ["Luxurious feel", "Jewelry storage", "Various colors"],
        specifications: { Material: "Velvet", Closure: "Drawstring", Size: "Small" },
        variations: [
            { name: "Small Velvet Pouch", price: "$8", image: "/images/velvet-pouch-small.png" },
            { name: "Large Velvet Pouch", price: "$15", image: "/images/velvet-pouch-large.png" },
        ],
        faqs: [
            { question: "What colors are available?", answer: "Various colors including black, navy, burgundy, and custom colors." },
            { question: "Are they suitable for jewelry?", answer: "Yes, velvet pouches are perfect for protecting jewelry." },
        ],
    },
    {
        slug: "tote-pouches",
        name: "Tote Pouches",
        sectionId: "fashion-textile",
        price: "Starting from $12",
        rating: 4.5,
        reviews: 56,
        images: ["/images/tote-pouches1.png", "/images/tote-pouches2.png"],
        description: "Functional tote pouches for everyday use.",
        features: ["Durable construction", "Comfortable handles", "Custom designs"],
        specifications: { Material: "Canvas/Cotton", Handles: "Comfortable", Size: "Medium" },
        variations: [
            { name: "Canvas Tote Pouch", price: "$12", image: "/images/canvas-tote-pouch.png" },
            { name: "Cotton Tote Pouch", price: "$18", image: "/images/cotton-tote-pouch.png" },
        ],
        faqs: [
            { question: "What materials are used?", answer: "Canvas, cotton, and various durable fabrics." },
            { question: "Are the handles comfortable?", answer: "Yes, handles are designed for comfort during extended use." },
        ],
    },
    {
        slug: "silk-sensation-pouches",
        name: "Silk Sensation Pouches",
        sectionId: "fashion-textile",
        price: "Starting from $15",
        rating: 4.8,
        reviews: 123,
        images: ["/images/silk-sensation-pouches1.png", "/images/silk-sensation-pouches2.png"],
        description: "Premium silk pouches with luxurious feel.",
        features: ["Silk material", "Luxurious feel", "Premium quality"],
        specifications: { Material: "Silk", Quality: "Premium", Feel: "Luxurious" },
        variations: [
            { name: "Standard Silk Pouch", price: "$15", image: "/images/silk-pouch-standard.png" },
            { name: "Premium Silk Pouch", price: "$25", image: "/images/silk-pouch-premium.png" },
        ],
        faqs: [
            { question: "What type of silk is used?", answer: "High-quality mulberry silk for the best feel and durability." },
            { question: "Are they hand-wash only?", answer: "Yes, silk pouches require gentle hand washing to maintain quality." },
        ],
    },
    {
        slug: "zipper-pouches",
        name: "Zipper Pouches",
        sectionId: "fashion-textile",
        price: "Starting from $10",
        rating: 4.4,
        reviews: 78,
        images: ["/images/zipper-pouches1.png", "/images/zipper-pouches2.png"],
        description: "Secure zipper pouches for organizing small items.",
        features: ["Secure closure", "Organized storage", "Various sizes"],
        specifications: { Closure: "Zipper", Material: "Fabric", Size: "Various" },
        variations: [
            { name: "Small Zipper Pouch", price: "$10", image: "/images/zipper-pouch-small.png" },
            { name: "Large Zipper Pouch", price: "$18", image: "/images/zipper-pouch-large.png" },
        ],
        faqs: [
            { question: "What zipper types are used?", answer: "High-quality metal and plastic zippers for durability." },
            { question: "Are they waterproof?", answer: "Some pouches have waterproof lining for added protection." },
        ],
    },
    // Lifestyle
    {
        slug: "armband",
        name: "Armbands",
        sectionId: "fashion-textile",
        price: "Starting from $5",
        rating: 4.3,
        reviews: 45,
        images: ["/images/armband1.png", "/images/armband2.png"],
        description: "Sporty armbands for fitness and fashion.",
        features: ["Sporty design", "Secure fit", "Sweat resistant"],
        specifications: { Material: "Neoprene/Elastic", Fit: "Secure", Use: "Sports" },
        variations: [
            { name: "Basic Armband", price: "$5", image: "/images/armband-basic.png" },
            { name: "Premium Armband", price: "$12", image: "/images/armband-premium.png" },
        ],
        faqs: [
            { question: "What materials are used?", answer: "Neoprene, elastic, and moisture-wicking materials." },
            { question: "Are they adjustable?", answer: "Yes, most armbands have adjustable straps for perfect fit." },
        ],
    },
    {
        slug: "sash",
        name: "Fashion Sashes",
        sectionId: "fashion-textile",
        price: "Starting from $18",
        rating: 4.6,
        reviews: 89,
        images: ["/images/sash1.png", "/images/sash2.png"],
        description: "Elegant sashes for formal events and ceremonies.",
        features: ["Elegant design", "Premium materials", "Custom designs"],
        specifications: { Material: "Satin/Silk", Length: "Long", Style: "Formal" },
        variations: [
            { name: "Satin Sash", price: "$18", image: "/images/satin-sash.png" },
            { name: "Silk Sash", price: "$35", image: "/images/silk-sash.png" },
        ],
        faqs: [
            { question: "What colors are available?", answer: "Various colors including traditional and custom colors." },
            { question: "Can I get custom embroidery?", answer: "Yes, we can add custom embroidery, names, or logos." },
        ],
    },
    {
        slug: "hand-umbrella",
        name: "Hand Umbrellas",
        sectionId: "fashion-textile",
        price: "Starting from $25",
        rating: 4.7,
        reviews: 134,
        images: ["/images/hand-umbrella1.png", "/images/hand-umbrella2.png"],
        description: "Stylish hand umbrellas with custom designs.",
        features: ["Weather protection", "Custom designs", "Durable construction"],
        specifications: { Material: "Waterproof fabric", Frame: "Metal/Fiber", Size: "Compact" },
        variations: [
            { name: "Standard Umbrella", price: "$25", image: "/images/umbrella-standard.png" },
            { name: "Premium Umbrella", price: "$45", image: "/images/umbrella-premium.png" },
        ],
        faqs: [
            { question: "What frame materials are used?", answer: "Aluminum, steel, and fiberglass frames for durability." },
            { question: "Are they wind resistant?", answer: "Yes, umbrellas are designed to withstand moderate winds." },
        ],
    },
    {
        slug: "face-masks",
        name: "Custom Face Masks",
        sectionId: "fashion-textile",
        price: "Starting from $8",
        rating: 4.5,
        reviews: 234,
        images: ["/images/face-masks1.png", "/images/face-masks2.png"],
        description: "Comfortable custom face masks for protection and style.",
        features: ["Comfortable fit", "Custom designs", "Washable"],
        specifications: { Material: "Cotton/Bamboo", Layers: "Multi-layer", Fit: "Adjustable" },
        variations: [
            { name: "Cotton Face Mask", price: "$8", image: "/images/cotton-face-mask.png" },
            { name: "Bamboo Face Mask", price: "$12", image: "/images/bamboo-face-mask.png" },
        ],
        faqs: [
            { question: "What materials are used?", answer: "Cotton, bamboo, and other breathable materials." },
            { question: "Are they reusable?", answer: "Yes, all face masks are washable and reusable." },
        ],
    },
    {
        slug: "apron",
        name: "Custom Aprons",
        sectionId: "fashion-textile",
        price: "Starting from $20",
        rating: 4.6,
        reviews: 98,
        images: ["/images/apron1.png", "/images/apron2.png"],
        description: "Functional aprons for cooking, crafting, and work.",
        features: ["Protective design", "Pocket options", "Custom branding"],
        specifications: { Material: "Cotton/Canvas", Pockets: "Optional", Straps: "Adjustable" },
        variations: [
            { name: "Basic Apron", price: "$20", image: "/images/apron-basic.png" },
            { name: "Premium Apron", price: "$35", image: "/images/apron-premium.png" },
        ],
        faqs: [
            { question: "What styles are available?", answer: "Bib aprons, waist aprons, and custom styles available." },
            { question: "Can I add pockets?", answer: "Yes, we can add various pocket configurations." },
        ],
    },
    // Dining
    {
        slug: "placemat",
        name: "Custom Placemats",
        sectionId: "fashion-textile",
        price: "Starting from $8",
        rating: 4.4,
        reviews: 67,
        images: ["/images/placemat1.png", "/images/placemat2.png"],
        description: "Beautiful placemats for dining and decoration.",
        features: ["Easy to clean", "Custom designs", "Various materials"],
        specifications: { Material: "Fabric/Vinyl", Size: "Standard", Cleaning: "Easy" },
        variations: [
            { name: "Fabric Placemat", price: "$8", image: "/images/fabric-placemat.png" },
            { name: "Vinyl Placemat", price: "$12", image: "/images/vinyl-placemat.png" },
        ],
        faqs: [
            { question: "What materials are available?", answer: "Fabric, vinyl, and various washable materials." },
            { question: "Are they machine washable?", answer: "Yes, most placemats are machine washable or wipeable." },
        ],
    },
    {
        slug: "table-napkin",
        name: "Table Napkins",
        sectionId: "fashion-textile",
        price: "Starting from $6",
        rating: 4.3,
        reviews: 89,
        images: ["/images/table-napkin1.png", "/images/table-napkin2.png"],
        description: "Elegant table napkins for dining and events.",
        features: ["Premium materials", "Custom designs", "Various sizes"],
        specifications: { Material: "Cotton/Linen", Size: "Standard", Design: "Custom" },
        variations: [
            { name: "Cotton Napkins", price: "$6", image: "/images/cotton-napkin.png" },
            { name: "Linen Napkins", price: "$12", image: "/images/linen-napkin.png" },
        ],
        faqs: [
            { question: "What sizes are available?", answer: "Standard dinner napkins and various custom sizes." },
            { question: "Can I get custom embroidery?", answer: "Yes, we can add custom embroidery or monograms." },
        ],
    },
    {
        slug: "dinning-table-cloth",
        name: "Dining Table Cloths",
        sectionId: "fashion-textile",
        price: "Starting from $35",
        rating: 4.7,
        reviews: 112,
        images: ["/images/dinning-table-cloth1.png", "/images/dinning-table-cloth2.png"],
        description: "Beautiful dining table cloths for elegant dining.",
        features: ["Elegant design", "Easy care", "Custom sizes"],
        specifications: { Material: "Cotton/Polyester", Size: "Custom", Care: "Easy" },
        variations: [
            { name: "Cotton Table Cloth", price: "$35", image: "/images/cotton-table-cloth.png" },
            { name: "Polyester Table Cloth", price: "$25", image: "/images/polyester-table-cloth.png" },
        ],
        faqs: [
            { question: "What table sizes are available?", answer: "Standard sizes plus custom dimensions for any table." },
            { question: "Are they wrinkle resistant?", answer: "Polyester options are wrinkle resistant, cotton options need ironing." },
        ],
    },
    // Fabric Range
    {
        slug: "haute-couture",
        name: "Haute Couture Fabrics",
        sectionId: "fashion-textile",
        price: "Starting from $85",
        rating: 4.9,
        reviews: 45,
        images: ["/images/haute-couture1.png", "/images/haute-couture2.png"],
        description: "Luxurious haute couture fabrics for high-end fashion.",
        features: ["Luxurious materials", "Premium quality", "Designer grade"],
        specifications: { Material: "Premium", Quality: "Haute couture", Grade: "Designer" },
        variations: [
            { name: "Silk Haute Couture", price: "$85", image: "/images/silk-haute-couture.png" },
            { name: "Velvet Haute Couture", price: "$95", image: "/images/velvet-haute-couture.png" },
        ],
        faqs: [
            { question: "What makes it haute couture?", answer: "Premium materials, exceptional craftsmanship, and designer quality." },
            { question: "Is it suitable for formal wear?", answer: "Yes, perfect for formal wear and special occasions." },
        ],
    },
    {
        slug: "fashion-wear",
        name: "Fashion Wear Fabrics",
        sectionId: "fashion-textile",
        price: "Starting from $25",
        rating: 4.6,
        reviews: 156,
        images: ["/images/fashion-wear1.png", "/images/fashion-wear2.png"],
        description: "Trendy fabrics for everyday fashion and casual wear.",
        features: ["Trendy designs", "Comfortable", "Various styles"],
        specifications: { Material: "Cotton/Polyester", Style: "Casual", Comfort: "High" },
        variations: [
            { name: "Cotton Fashion Wear", price: "$25", image: "/images/cotton-fashion-wear.png" },
            { name: "Polyester Fashion Wear", price: "$20", image: "/images/polyester-fashion-wear.png" },
        ],
        faqs: [
            { question: "What styles are available?", answer: "Various styles from casual to semi-formal fashion." },
            { question: "Are they easy to care for?", answer: "Yes, most fashion wear fabrics are machine washable." },
        ],
    },
    {
        slug: "decor-fabric",
        name: "Décor Fabrics",
        sectionId: "fashion-textile",
        price: "Starting from $35",
        rating: 4.8,
        reviews: 134,
        images: ["/images/decor-fabric1.png", "/images/decor-fabric2.png"],
        description: "Beautiful décor fabrics for home and office decoration.",
        features: ["Decorative designs", "Durable", "Various patterns"],
        specifications: { Material: "Decorative", Use: "Home/Office", Durability: "High" },
        variations: [
            { name: "Home Décor Fabric", price: "$35", image: "/images/home-decor-fabric.png" },
            { name: "Office Décor Fabric", price: "$45", image: "/images/office-decor-fabric.png" },
        ],
        faqs: [
            { question: "What patterns are available?", answer: "Various patterns including floral, geometric, and abstract designs." },
            { question: "Are they suitable for upholstery?", answer: "Yes, many décor fabrics are suitable for upholstery projects." },
        ],
    },
    // Patterns
    {
        slug: "floral",
        name: "Floral Patterns",
        sectionId: "fashion-textile",
        price: "Starting from $20",
        rating: 4.7,
        reviews: 189,
        images: ["/images/floral1.png", "/images/floral2.png"],
        description: "Beautiful floral patterns for fashion and decoration.",
        features: ["Natural designs", "Various flowers", "Colorful patterns"],
        specifications: { Design: "Floral", Colors: "Various", Style: "Natural" },
        variations: [
            { name: "Small Floral Pattern", price: "$20", image: "/images/floral-small.png" },
            { name: "Large Floral Pattern", price: "$35", image: "/images/floral-large.png" },
        ],
        faqs: [
            { question: "What flower types are available?", answer: "Various flowers including roses, daisies, and tropical flowers." },
            { question: "Can I get custom floral designs?", answer: "Yes, we can create custom floral patterns from your specifications." },
        ],
    },
    {
        slug: "geometric",
        name: "Geometric Patterns",
        sectionId: "fashion-textile",
        price: "Starting from $18",
        rating: 4.5,
        reviews: 98,
        images: ["/images/geometric1.png", "/images/geometric2.png"],
        description: "Modern geometric patterns for contemporary design.",
        features: ["Modern design", "Mathematical precision", "Bold patterns"],
        specifications: { Design: "Geometric", Style: "Modern", Precision: "Mathematical" },
        variations: [
            { name: "Simple Geometric", price: "$18", image: "/images/geometric-simple.png" },
            { name: "Complex Geometric", price: "$30", image: "/images/geometric-complex.png" },
        ],
        faqs: [
            { question: "What shapes are available?", answer: "Various shapes including triangles, squares, circles, and complex patterns." },
            { question: "Are they suitable for modern décor?", answer: "Yes, geometric patterns are perfect for modern and contemporary spaces." },
        ],
    },
    {
        slug: "landscape",
        name: "Landscape Patterns",
        sectionId: "fashion-textile",
        price: "Starting from $40",
        rating: 4.8,
        reviews: 67,
        images: ["/images/landscape1.png", "/images/landscape2.png"],
        description: "Scenic landscape patterns for artistic decoration.",
        features: ["Artistic designs", "Natural scenes", "Detailed patterns"],
        specifications: { Design: "Landscape", Style: "Artistic", Detail: "High" },
        variations: [
            { name: "Mountain Landscape", price: "$40", image: "/images/mountain-landscape.png" },
            { name: "Ocean Landscape", price: "$45", image: "/images/ocean-landscape.png" },
        ],
        faqs: [
            { question: "What landscapes are available?", answer: "Mountains, oceans, forests, and various scenic landscapes." },
            { question: "Are they suitable for wall hangings?", answer: "Yes, landscape patterns work beautifully as wall hangings and décor." },
        ],
    },
]
