// Office & Store Branding Products

import { Product } from './types'

export const officeBrandingProducts: Product[] = [
    {
        slug: "reverse-cut-frosted-sticker",
        name: "Reverse Cut Frosted Stickers",
        sectionId: "office-branding",
        price: "Starting from $25",
        rating: 4.7,
        reviews: 89,
        images: ["/products/02 Sticker's/pvc_transparent_stickers_printing_Sharjah.jpg", "/products/02 Sticker's/white_ink_stickers _sharjah.jpg"],
        description: "Professional reverse cut frosted stickers for office windows and glass surfaces.",
        features: ["Privacy protection", "Professional appearance", "Easy application"],
        specifications: { Material: "Frosted vinyl", Cut: "Reverse cut", Application: "Professional" },
        variations: [
            { name: "Standard Reverse Cut", price: "$25", image: "/images/reverse-cut-standard.png" },
            { name: "Premium Reverse Cut", price: "$35", image: "/images/reverse-cut-premium.png" },
        ],
        faqs: [
            { question: "What's reverse cut?", answer: "Reverse cut means the design is cut from the back, creating a clean look." },
            { question: "Is it removable?", answer: "Yes, designed for easy removal without residue." },
        ],
    },
    {
        slug: "standard-cut-frosted-sticker",
        name: "Standard Cut Frosted Stickers",
        sectionId: "office-branding",
        price: "Starting from $20",
        rating: 4.6,
        reviews: 67,
        images: ["/products/02 Sticker's/pvc_transparent_stickers_printing_Sharjah.jpg", "/products/02 Sticker's/white_ink_stickers _sharjah.jpg"],
        description: "Standard cut frosted stickers for office branding and privacy.",
        features: ["Cost-effective", "Professional finish", "Custom designs"],
        specifications: { Material: "Frosted vinyl", Cut: "Standard cut", Size: "Custom" },
        variations: [
            { name: "Standard Frosted", price: "$20", image: "/images/standard-frosted.png" },
            { name: "Premium Frosted", price: "$30", image: "/images/premium-frosted.png" },
        ],
        faqs: [
            { question: "What's the difference from reverse cut?", answer: "Standard cut is more cost-effective with slightly less precision." },
            { question: "Can I customize the design?", answer: "Yes, we can create custom designs for your branding needs." },
        ],
    },
    {
        slug: "printed-frosted-sticker",
        name: "Printed Frosted Stickers",
        sectionId: "office-branding",
        price: "Starting from $35",
        rating: 4.8,
        reviews: 112,
        images: ["/products/02 Sticker's/print_and_cut_stickers_sharjah.jpg", "/products/02 Sticker's/paper_sticker_printing_sharjah.jpg"],
        description: "High-quality printed frosted stickers with custom graphics and text.",
        features: ["Full-color printing", "Custom graphics", "Professional finish"],
        specifications: { Material: "Frosted vinyl", Printing: "Full color", Design: "Custom" },
        variations: [
            { name: "Basic Printed Frosted", price: "$35", image: "/images/printed-basic.png" },
            { name: "Premium Printed Frosted", price: "$55", image: "/images/printed-premium.png" },
        ],
        faqs: [
            { question: "What printing method is used?", answer: "We use high-quality digital printing for vibrant colors." },
            { question: "Can I add my logo?", answer: "Yes, we can incorporate your logo and branding elements." },
        ],
    },
    {
        slug: "blank-frosted-sticker",
        name: "Blank Frosted Stickers",
        sectionId: "office-branding",
        price: "Starting from $15",
        rating: 4.4,
        reviews: 45,
        images: ["/images/blank-frosted1.png", "/images/blank-frosted2.png"],
        description: "Blank frosted stickers for DIY projects and custom applications.",
        features: ["Blank design", "DIY friendly", "Cost-effective"],
        specifications: { Material: "Frosted vinyl", Design: "Blank", Application: "DIY" },
        variations: [
            { name: "Small Blank Frosted", price: "$15", image: "/images/blank-small.png" },
            { name: "Large Blank Frosted", price: "$25", image: "/images/blank-large.png" },
        ],
        faqs: [
            { question: "What sizes are available?", answer: "Various sizes from small to large available." },
            { question: "Can I write on them?", answer: "Yes, suitable for writing with permanent markers." },
        ],
    },
    {
        slug: "window-vinyl-lettering",
        name: "Window Vinyl Lettering",
        sectionId: "office-branding",
        price: "Starting from $30",
        rating: 4.7,
        reviews: 134,
        images: ["/images/window-vinyl-lettering1.png", "/images/window-vinyl-lettering2.png"],
        description: "Professional window vinyl lettering for business identification and branding.",
        features: ["Professional finish", "Weather resistant", "Custom fonts"],
        specifications: { Material: "Vinyl", Application: "Window", Font: "Custom options" },
        variations: [
            { name: "Standard Window Lettering", price: "$30", image: "/images/window-lettering-standard.png" },
            { name: "Premium Window Lettering", price: "$45", image: "/images/window-lettering-premium.png" },
        ],
        faqs: [
            { question: "What fonts are available?", answer: "We have hundreds of fonts available or can use your custom font." },
            { question: "How long does it last?", answer: "Window lettering can last 3-5 years with proper care." },
        ],
    },
    {
        slug: "window-graphics",
        name: "Window Graphics",
        sectionId: "office-branding",
        price: "Starting from $25",
        rating: 4.7,
        reviews: 156,
        images: ["/images/window-graphics1.png", "/images/window-graphics2.png"],
        description: "Professional window graphics for branding and decoration.",
        features: ["Weather resistant", "Custom designs", "Professional finish"],
        specifications: { Material: "Vinyl", Printing: "Full color", Installation: "Professional" },
        variations: [
            { name: "Window Lettering", price: "$25", image: "/images/window-lettering.png" },
            { name: "Window Graphics", price: "$35", image: "/images/window-graphics-variation.png" }
        ],
        faqs: [
            { question: "How long do they last?", answer: "Window graphics can last 3-5 years with proper care." },
            { question: "Can they be applied to any window?", answer: "Yes, suitable for most glass surfaces." }
        ],
    },
    {
        slug: "one-way-vision-sticker",
        name: "One Way Vision Stickers",
        sectionId: "office-branding",
        price: "Starting from $40",
        rating: 4.8,
        reviews: 98,
        images: ["/images/one-way-vision1.png", "/images/one-way-vision2.png"],
        description: "One-way vision stickers for windows that provide privacy while maintaining visibility.",
        features: ["One-way visibility", "Privacy protection", "Professional appearance"],
        specifications: { Material: "Special vinyl", Visibility: "One-way", Application: "Professional" },
        variations: [
            { name: "Standard One Way Vision", price: "$40", image: "/images/one-way-standard.png" },
            { name: "Premium One Way Vision", price: "$60", image: "/images/one-way-premium.png" },
        ],
        faqs: [
            { question: "How does one-way vision work?", answer: "Allows visibility from inside while providing privacy from outside." },
            { question: "Is it suitable for all windows?", answer: "Yes, suitable for most glass surfaces." },
        ],
    },
    {
        slug: "window-films",
        name: "Window Films",
        sectionId: "office-branding",
        price: "Starting from $35",
        rating: 4.6,
        reviews: 76,
        images: ["/images/window-films1.png", "/images/window-films2.png"],
        description: "Professional window films for privacy, decoration, and UV protection.",
        features: ["UV protection", "Privacy enhancement", "Energy efficiency"],
        specifications: { Material: "Window film", Features: "UV protection", Application: "Professional" },
        variations: [
            { name: "Privacy Window Film", price: "$35", image: "/images/window-film-privacy.png" },
            { name: "UV Protection Film", price: "$55", image: "/images/window-film-uv.png" },
        ],
        faqs: [
            { question: "Does it block UV rays?", answer: "Yes, our films block up to 99% of UV rays." },
            { question: "Can it be removed?", answer: "Yes, designed for easy removal without damage." },
        ],
    },
    {
        slug: "wall-vinyl-lettering",
        name: "Wall Vinyl Lettering",
        sectionId: "office-branding",
        price: "Starting from $25",
        rating: 4.5,
        reviews: 89,
        images: ["/images/wall-vinyl-lettering1.png", "/images/wall-vinyl-lettering2.png"],
        description: "Professional wall vinyl lettering for office branding and decoration.",
        features: ["Professional finish", "Custom designs", "Easy application"],
        specifications: { Material: "Vinyl", Application: "Wall", Design: "Custom" },
        variations: [
            { name: "Standard Wall Lettering", price: "$25", image: "/images/wall-lettering-standard.png" },
            { name: "Premium Wall Lettering", price: "$40", image: "/images/wall-lettering-premium.png" },
        ],
        faqs: [
            { question: "What surfaces can it be applied to?", answer: "Suitable for most smooth surfaces including walls and doors." },
            { question: "Is it removable?", answer: "Yes, can be removed without damaging the surface." },
        ],
    },
    {
        slug: "wall-sticker",
        name: "Wall Stickers",
        sectionId: "office-branding",
        price: "Starting from $20",
        rating: 4.4,
        reviews: 67,
        images: ["/images/wall-sticker1.png", "/images/wall-sticker2.png"],
        description: "Decorative wall stickers for office branding and interior decoration.",
        features: ["Decorative design", "Easy application", "Custom options"],
        specifications: { Material: "Vinyl", Application: "Wall", Design: "Decorative" },
        variations: [
            { name: "Basic Wall Sticker", price: "$20", image: "/images/wall-sticker-basic.png" },
            { name: "Premium Wall Sticker", price: "$35", image: "/images/wall-sticker-premium.png" },
        ],
        faqs: [
            { question: "What designs are available?", answer: "Various decorative designs or custom designs available." },
            { question: "Can it be repositioned?", answer: "Yes, most wall stickers can be repositioned during application." },
        ],
    },
    {
        slug: "wall-decal",
        name: "Wall Decals",
        sectionId: "office-branding",
        price: "Starting from $30",
        rating: 4.6,
        reviews: 78,
        images: ["/images/wall-decal1.png", "/images/wall-decal2.png"],
        description: "Professional wall decals for office branding and interior design.",
        features: ["Professional appearance", "Custom designs", "High-quality materials"],
        specifications: { Material: "Premium vinyl", Application: "Wall", Quality: "Professional" },
        variations: [
            { name: "Standard Wall Decal", price: "$30", image: "/images/wall-decal-standard.png" },
            { name: "Premium Wall Decal", price: "$50", image: "/images/wall-decal-premium.png" },
        ],
        faqs: [
            { question: "What's the difference from wall stickers?", answer: "Decals are typically higher quality and more professional." },
            { question: "Can I get custom designs?", answer: "Yes, we can create custom wall decals for your branding." },
        ],
    },
    {
        slug: "bedroom-wallpaper",
        name: "Bedroom Wallpaper",
        sectionId: "office-branding",
        price: "Starting from $45",
        rating: 4.7,
        reviews: 112,
        images: ["/images/bedroom-wallpaper1.png", "/images/bedroom-wallpaper2.png"],
        description: "Elegant bedroom wallpaper for office spaces and private areas.",
        features: ["Elegant design", "Easy installation", "High-quality materials"],
        specifications: { Material: "Wallpaper", Application: "Bedroom", Design: "Elegant" },
        variations: [
            { name: "Standard Bedroom Wallpaper", price: "$45", image: "/images/bedroom-wallpaper-standard.png" },
            { name: "Premium Bedroom Wallpaper", price: "$65", image: "/images/bedroom-wallpaper-premium.png" },
        ],
        faqs: [
            { question: "Is it easy to install?", answer: "Yes, designed for easy installation with proper preparation." },
            { question: "What patterns are available?", answer: "Various patterns from subtle to bold designs available." },
        ],
    },
    {
        slug: "living-room-wallpaper",
        name: "Living Room Wallpaper",
        sectionId: "office-branding",
        price: "Starting from $50",
        rating: 4.8,
        reviews: 134,
        images: ["/images/living-room-wallpaper1.png", "/images/living-room-wallpaper2.png"],
        description: "Premium living room wallpaper for reception areas and common spaces.",
        features: ["Premium design", "Professional appearance", "Durable materials"],
        specifications: { Material: "Premium wallpaper", Application: "Living room", Quality: "Premium" },
        variations: [
            { name: "Standard Living Room Wallpaper", price: "$50", image: "/images/living-room-wallpaper-standard.png" },
            { name: "Premium Living Room Wallpaper", price: "$75", image: "/images/living-room-wallpaper-premium.png" },
        ],
        faqs: [
            { question: "What styles are available?", answer: "Various styles from modern to traditional available." },
            { question: "Is it suitable for commercial use?", answer: "Yes, designed for both residential and commercial applications." },
        ],
    },
    {
        slug: "wall-frames",
        name: "Wall Frames",
        sectionId: "office-branding",
        price: "Starting from $35",
        rating: 4.8,
        reviews: 203,
        images: ["/images/wall-frames1.png", "/images/wall-frames2.png"],
        description: "Elegant wall frames for office decoration and branding.",
        features: ["Multiple materials", "Custom sizes", "Professional mounting"],
        specifications: { Material: "Wood/Metal/Acrylic", Sizes: "Custom", Finish: "Various options" },
        variations: [
            { name: "Canvas Frames", price: "$35", image: "/images/canvas-frames.png" },
            { name: "Wooden Frames", price: "$45", image: "/images/wooden-frames.png" },
            { name: "Acrylic Frames", price: "$55", image: "/images/acrylic-frames.png" }
        ],
        faqs: [
            { question: "Do you provide installation?", answer: "Yes, professional installation service available." },
            { question: "What materials are available?", answer: "Wood, metal, acrylic, and canvas options." }
        ],
    },
    {
        slug: "frosted-stickers",
        name: "Frosted Stickers",
        sectionId: "office-branding",
        price: "Starting from $15",
        rating: 4.6,
        reviews: 89,
        images: ["/images/frosted-stickers1.png", "/images/frosted-stickers2.png"],
        description: "Elegant frosted stickers for office branding and privacy.",
        features: ["Privacy protection", "Easy application", "Durable material"],
        specifications: { Material: "Frosted vinyl", Size: "Custom", Adhesive: "Removable" },
        variations: [
            { name: "Standard Frosted", price: "$15", image: "/images/frosted-standard.png" },
            { name: "Reverse Cut", price: "$18", image: "/images/frosted-reverse.png" }
        ],
        faqs: [
            { question: "Can these be removed easily?", answer: "Yes, they are designed for easy removal without residue." },
            { question: "Do they provide privacy?", answer: "Yes, they offer 90% privacy while maintaining light transmission." }
        ],
    },
    // --- MISSING OFFICE & STORE BRANDING PRODUCTS ---
    {
        slug: "metal-art",
        name: "Metal Art",
        sectionId: "office-branding",
        price: "Starting from $65",
        rating: 4.8,
        reviews: 98,
        images: ["/images/metal-art1.png", "/images/metal-art2.png"],
        description: "Elegant metal art pieces for office decoration and branding.",
        features: ["Metal construction", "Custom designs", "Professional finish"],
        specifications: { Material: "Metal", Design: "Custom", Finish: "Professional" },
        variations: [
            { name: "Steel Metal Art", price: "$65", image: "/images/steel-metal-art.png" },
            { name: "Aluminum Metal Art", price: "$85", image: "/images/aluminum-metal-art.png" },
        ],
        faqs: [
            { question: "What metals are used?", answer: "Steel, aluminum, and various metal alloys available." },
            { question: "Can I get custom designs?", answer: "Yes, we can create custom metal art from your specifications." },
        ],
    },
    {
        slug: "floor-display-gondola",
        name: "Floor Display Gondola",
        sectionId: "office-branding",
        price: "Starting from $125",
        rating: 4.7,
        reviews: 67,
        images: ["/images/floor-display-gondola1.png", "/images/floor-display-gondola2.png"],
        description: "Professional floor display gondola for retail and exhibitions.",
        features: ["Modular design", "Custom branding", "Professional appearance"],
        specifications: { Material: "Metal/Wood", Modular: "Yes", Branding: "Custom" },
        variations: [
            { name: "Standard Gondola", price: "$125", image: "/images/gondola-standard.png" },
            { name: "Premium Gondola", price: "$185", image: "/images/gondola-premium.png" },
        ],
        faqs: [
            { question: "Is it modular?", answer: "Yes, gondola systems are modular and can be configured as needed." },
            { question: "Can I add custom branding?", answer: "Yes, we can add custom graphics and branding elements." },
        ],
    },
    {
        slug: "3d-display-stand",
        name: "3D Display Stand",
        sectionId: "office-branding",
        price: "Starting from $45",
        rating: 4.6,
        reviews: 89,
        images: ["/images/3d-display-stand1.png", "/images/3d-display-stand2.png"],
        description: "Eye-catching 3D display stands for products and information.",
        features: ["3D design", "Easy assembly", "Custom graphics"],
        specifications: { Design: "3D", Assembly: "Easy", Graphics: "Custom" },
        variations: [
            { name: "Standard 3D Stand", price: "$45", image: "/images/3d-stand-standard.png" },
            { name: "Premium 3D Stand", price: "$65", image: "/images/3d-stand-premium.png" },
        ],
        faqs: [
            { question: "How easy is assembly?", answer: "Very easy, most stands can be assembled in under 10 minutes." },
            { question: "Can I add custom graphics?", answer: "Yes, we can print custom graphics on the display stands." },
        ],
    },
    {
        slug: "counter-top-stand",
        name: "Counter Top Stand",
        sectionId: "office-branding",
        price: "Starting from $25",
        rating: 4.5,
        reviews: 134,
        images: ["/images/counter-top-stand1.png", "/images/counter-top-stand2.png"],
        description: "Compact counter top stands for point-of-sale displays.",
        features: ["Compact design", "Professional finish", "Custom branding"],
        specifications: { Size: "Compact", Use: "Counter top", Branding: "Custom" },
        variations: [
            { name: "Basic Counter Stand", price: "$25", image: "/images/counter-stand-basic.png" },
            { name: "Premium Counter Stand", price: "$40", image: "/images/counter-stand-premium.png" },
        ],
        faqs: [
            { question: "What sizes are available?", answer: "Various compact sizes suitable for counter tops." },
            { question: "Is it easy to clean?", answer: "Yes, designed for easy cleaning and maintenance." },
        ],
    },
    {
        slug: "large-posters",
        name: "Large Posters",
        sectionId: "office-branding",
        price: "Starting from $35",
        rating: 4.7,
        reviews: 156,
        images: ["/images/large-posters1.png", "/images/large-posters2.png"],
        description: "High-quality large posters for advertising and decoration.",
        features: ["High resolution", "Large format", "Professional printing"],
        specifications: { Size: "Large format", Printing: "High quality", Material: "Paper/Vinyl" },
        variations: [
            { name: "Paper Large Poster", price: "$35", image: "/images/large-poster-paper.png" },
            { name: "Vinyl Large Poster", price: "$55", image: "/images/large-poster-vinyl.png" },
        ],
        faqs: [
            { question: "What sizes are available?", answer: "Various large sizes from A1 to custom dimensions." },
            { question: "What printing methods are used?", answer: "High-quality digital printing for vibrant colors." },
        ],
    },
    {
        slug: "wall-mounted-posters",
        name: "Wall Mounted Posters",
        sectionId: "office-branding",
        price: "Starting from $30",
        rating: 4.6,
        reviews: 98,
        images: ["/images/wall-mounted-posters1.png", "/images/wall-mounted-posters2.png"],
        description: "Professional wall mounted posters with framing options.",
        features: ["Wall mounting", "Framing options", "Professional finish"],
        specifications: { Mounting: "Wall", Framing: "Optional", Finish: "Professional" },
        variations: [
            { name: "Basic Wall Poster", price: "$30", image: "/images/wall-poster-basic.png" },
            { name: "Framed Wall Poster", price: "$65", image: "/images/wall-poster-framed.png" },
        ],
        faqs: [
            { question: "Do you provide mounting hardware?", answer: "Yes, appropriate mounting hardware is included." },
            { question: "Can I get custom framing?", answer: "Yes, we offer various framing options for wall posters." },
        ],
    },
    {
        slug: "hanging-posters",
        name: "Hanging Posters",
        sectionId: "office-branding",
        price: "Starting from $28",
        rating: 4.4,
        reviews: 67,
        images: ["/images/hanging-posters1.png", "/images/hanging-posters2.png"],
        description: "Hanging posters for ceiling and overhead displays.",
        features: ["Hanging system", "Easy installation", "Custom designs"],
        specifications: { Method: "Hanging", Installation: "Easy", Design: "Custom" },
        variations: [
            { name: "Standard Hanging Poster", price: "$28", image: "/images/hanging-poster-standard.png" },
            { name: "Premium Hanging Poster", price: "$45", image: "/images/hanging-poster-premium.png" },
        ],
        faqs: [
            { question: "How are they hung?", answer: "Using ceiling hooks, chains, or custom hanging systems." },
            { question: "What's the weight limit?", answer: "Designed to support standard poster weights safely." },
        ],
    },
    {
        slug: "car-magnets",
        name: "Car Magnets",
        sectionId: "office-branding",
        price: "Starting from $25",
        rating: 4.8,
        reviews: 189,
        images: ["/images/car-magnets1.png", "/images/car-magnets2.png"],
        description: "Strong car magnets for vehicle advertising and branding.",
        features: ["Strong magnetic hold", "Weather resistant", "Removable"],
        specifications: { Material: "Magnetic", Strength: "Strong", Weather: "Resistant" },
        variations: [
            { name: "Standard Car Magnet", price: "$25", image: "/images/car-magnet-standard.png" },
            { name: "Premium Car Magnet", price: "$40", image: "/images/car-magnet-premium.png" },
        ],
        faqs: [
            { question: "How strong is the magnetic hold?", answer: "Very strong, designed to stay in place during normal driving." },
            { question: "Are they weather resistant?", answer: "Yes, designed to withstand outdoor weather conditions." },
        ],
    },
    {
        slug: "fridge-magnets",
        name: "Fridge Magnets",
        sectionId: "office-branding",
        price: "Starting from $8",
        rating: 4.6,
        reviews: 234,
        images: ["/images/fridge-magnets1.png", "/images/fridge-magnets2.png"],
        description: "Custom fridge magnets for advertising and decoration.",
        features: ["Custom designs", "Strong magnetic hold", "Various shapes"],
        specifications: { Material: "Magnetic", Shape: "Various", Design: "Custom" },
        variations: [
            { name: "Basic Fridge Magnet", price: "$8", image: "/images/fridge-magnet-basic.png" },
            { name: "Premium Fridge Magnet", price: "$15", image: "/images/fridge-magnet-premium.png" },
        ],
        faqs: [
            { question: "What shapes are available?", answer: "Various shapes including rectangular, circular, and custom shapes." },
            { question: "Can I get custom designs?", answer: "Yes, we can create custom designs for your fridge magnets." },
        ],
    },
    {
        slug: "magnetic-wall",
        name: "Magnetic Wall Systems",
        sectionId: "office-branding",
        price: "Starting from $85",
        rating: 4.7,
        reviews: 78,
        images: ["/images/magnetic-wall1.png", "/images/magnetic-wall2.png"],
        description: "Magnetic wall systems for flexible displays and organization.",
        features: ["Magnetic surface", "Modular design", "Easy reconfiguration"],
        specifications: { Material: "Magnetic", Modular: "Yes", Reconfiguration: "Easy" },
        variations: [
            { name: "Standard Magnetic Wall", price: "$85", image: "/images/magnetic-wall-standard.png" },
            { name: "Premium Magnetic Wall", price: "$125", image: "/images/magnetic-wall-premium.png" },
        ],
        faqs: [
            { question: "How strong is the magnetic surface?", answer: "Strong enough to hold various display materials securely." },
            { question: "Can it be painted?", answer: "Yes, magnetic walls can be painted to match your décor." },
        ],
    },
    {
        slug: "domed-magnet",
        name: "Domed Magnets",
        sectionId: "office-branding",
        price: "Starting from $12",
        rating: 4.5,
        reviews: 89,
        images: ["/images/domed-magnet1.png", "/images/domed-magnet2.png"],
        description: "Domed magnets with raised, glossy finish for premium appearance.",
        features: ["Domed finish", "Glossy appearance", "Premium look"],
        specifications: { Finish: "Domed", Appearance: "Glossy", Quality: "Premium" },
        variations: [
            { name: "Standard Domed Magnet", price: "$12", image: "/images/domed-magnet-standard.png" },
            { name: "Premium Domed Magnet", price: "$20", image: "/images/domed-magnet-premium.png" },
        ],
        faqs: [
            { question: "What is a domed finish?", answer: "A raised, glossy finish that provides a premium, tactile appearance." },
            { question: "Are they durable?", answer: "Yes, domed magnets are highly durable and long-lasting." },
        ],
    },
    {
        slug: "car-branding",
        name: "Car Branding",
        sectionId: "office-branding",
        price: "Starting from $299",
        rating: 4.8,
        reviews: 134,
        images: ["/images/car-branding1.png", "/images/car-branding2.png"],
        description: "Complete car branding solutions for mobile advertising.",
        features: ["Full vehicle coverage", "Professional installation", "Weather resistant"],
        specifications: { Coverage: "Full vehicle", Installation: "Professional", Durability: "Weather resistant" },
        variations: [
            { name: "Partial Car Branding", price: "$299", image: "/images/car-branding-partial.png" },
            { name: "Full Car Branding", price: "$599", image: "/images/car-branding-full.png" },
        ],
        faqs: [
            { question: "How long does installation take?", answer: "Installation typically takes 1-2 days depending on complexity." },
            { question: "Is it removable?", answer: "Yes, car branding can be removed without damaging the vehicle paint." },
        ],
    },
    {
        slug: "boat-yacht-branding",
        name: "Boat/Yacht Branding",
        sectionId: "office-branding",
        price: "Starting from $450",
        rating: 4.9,
        reviews: 45,
        images: ["/images/boat-yacht-branding1.png", "/images/boat-yacht-branding2.png"],
        description: "Marine-grade branding solutions for boats and yachts.",
        features: ["Marine grade materials", "Salt water resistant", "Professional installation"],
        specifications: { Grade: "Marine", Resistance: "Salt water", Installation: "Professional" },
        variations: [
            { name: "Boat Branding", price: "$450", image: "/images/boat-branding.png" },
            { name: "Yacht Branding", price: "$850", image: "/images/yacht-branding.png" },
        ],
        faqs: [
            { question: "Are materials marine grade?", answer: "Yes, all materials are specifically designed for marine environments." },
            { question: "How long does it last in salt water?", answer: "Marine-grade materials can last 3-5 years in salt water conditions." },
        ],
    },
    {
        slug: "clear-static-cling",
        name: "Clear Static Cling",
        sectionId: "office-branding",
        price: "Starting from $15",
        rating: 4.4,
        reviews: 67,
        images: ["/images/clear-static-cling1.png", "/images/clear-static-cling2.png"],
        description: "Clear static cling for temporary window displays.",
        features: ["Clear appearance", "Static cling", "Temporary use"],
        specifications: { Material: "Static cling", Appearance: "Clear", Use: "Temporary" },
        variations: [
            { name: "Standard Clear Cling", price: "$15", image: "/images/clear-cling-standard.png" },
            { name: "Premium Clear Cling", price: "$25", image: "/images/clear-cling-premium.png" },
        ],
        faqs: [
            { question: "How does static cling work?", answer: "Uses static electricity to adhere to smooth surfaces without adhesive." },
            { question: "Is it reusable?", answer: "Yes, static cling can be removed and reapplied multiple times." },
        ],
    },
    {
        slug: "shape-cut-out-cling",
        name: "Shape Cut Out Cling",
        sectionId: "office-branding",
        price: "Starting from $20",
        rating: 4.6,
        reviews: 89,
        images: ["/images/shape-cut-out-cling1.png", "/images/shape-cut-out-cling2.png"],
        description: "Custom shaped cut-out cling for creative displays.",
        features: ["Custom shapes", "Static cling", "Creative designs"],
        specifications: { Shape: "Custom", Method: "Cut out", Cling: "Static" },
        variations: [
            { name: "Basic Shape Cut Out", price: "$20", image: "/images/shape-cutout-basic.png" },
            { name: "Premium Shape Cut Out", price: "$35", image: "/images/shape-cutout-premium.png" },
        ],
        faqs: [
            { question: "What shapes can be created?", answer: "Any custom shape can be cut out from your design." },
            { question: "Is it easy to apply?", answer: "Yes, static cling is very easy to apply and remove." },
        ],
    },
    {
        slug: "floor-direction-sticker",
        name: "Floor Direction Stickers",
        sectionId: "office-branding",
        price: "Starting from $12",
        rating: 4.5,
        reviews: 123,
        images: ["/images/floor-direction-sticker1.png", "/images/floor-direction-sticker2.png"],
        description: "Floor direction stickers for wayfinding and guidance.",
        features: ["Durable material", "Easy to clean", "High visibility"],
        specifications: { Material: "Vinyl", Durability: "High", Visibility: "High" },
        variations: [
            { name: "Standard Direction Sticker", price: "$12", image: "/images/direction-sticker-standard.png" },
            { name: "Premium Direction Sticker", price: "$20", image: "/images/direction-sticker-premium.png" },
        ],
        faqs: [
            { question: "Are they suitable for high traffic areas?", answer: "Yes, designed to withstand high foot traffic." },
            { question: "How long do they last?", answer: "Floor direction stickers can last 1-3 years depending on traffic." },
        ],
    },
    {
        slug: "footprint-floor-sticker",
        name: "Footprint Floor Stickers",
        sectionId: "office-branding",
        price: "Starting from $8",
        rating: 4.4,
        reviews: 78,
        images: ["/images/footprint-floor-sticker1.png", "/images/footprint-floor-sticker2.png"],
        description: "Footprint floor stickers for social distancing and guidance.",
        features: ["Social distancing", "Easy application", "Removable"],
        specifications: { Purpose: "Social distancing", Application: "Easy", Removal: "Easy" },
        variations: [
            { name: "Standard Footprint Sticker", price: "$8", image: "/images/footprint-sticker-standard.png" },
            { name: "Premium Footprint Sticker", price: "$15", image: "/images/footprint-sticker-premium.png" },
        ],
        faqs: [
            { question: "What are they used for?", answer: "Social distancing, wayfinding, and floor guidance systems." },
            { question: "Are they easy to remove?", answer: "Yes, designed for easy removal without leaving residue." },
        ],
    },
    {
        slug: "ceremonial-ribbon",
        name: "Ceremonial Ribbons",
        sectionId: "office-branding",
        price: "Starting from $18",
        rating: 4.7,
        reviews: 56,
        images: ["/images/ceremonial-ribbon1.png", "/images/ceremonial-ribbon2.png"],
        description: "Elegant ceremonial ribbons for events and celebrations.",
        features: ["Elegant design", "Custom colors", "Premium materials"],
        specifications: { Material: "Premium", Colors: "Custom", Quality: "High" },
        variations: [
            { name: "Standard Ceremonial Ribbon", price: "$18", image: "/images/ceremonial-ribbon-standard.png" },
            { name: "Premium Ceremonial Ribbon", price: "$35", image: "/images/ceremonial-ribbon-premium.png" },
        ],
        faqs: [
            { question: "What colors are available?", answer: "Various colors including traditional and custom colors." },
            { question: "Can I get custom printing?", answer: "Yes, we can add custom text, logos, or designs to ribbons." },
        ],
    },
    {
        slug: "counter-partition",
        name: "Counter Partitions",
        sectionId: "office-branding",
        price: "Starting from $75",
        rating: 4.6,
        reviews: 89,
        images: ["/images/counter-partition1.png", "/images/counter-partition2.png"],
        description: "Professional counter partitions for office and retail spaces.",
        features: ["Professional appearance", "Custom heights", "Easy installation"],
        specifications: { Material: "Acrylic/Glass", Height: "Custom", Installation: "Easy" },
        variations: [
            { name: "Acrylic Counter Partition", price: "$75", image: "/images/acrylic-partition.png" },
            { name: "Glass Counter Partition", price: "$125", image: "/images/glass-partition.png" },
        ],
        faqs: [
            { question: "What materials are available?", answer: "Acrylic, glass, and various transparent materials." },
            { question: "Can I get custom heights?", answer: "Yes, we can create partitions in custom heights for your space." },
        ],
    },
]
