// Print & Marketing Products

import { Product } from './types'

export const printMarketingProducts: Product[] = [
    {
        slug: "business-cards",
        name: "Premium Business Cards",
        sectionId: "print-marketing",
        price: "Starting from $25",
        rating: 4.9,
        reviews: 156,
        images: ["/images/business-card1.png", "/images/business-card2.png"],
        description: "Make a lasting impression with high-quality custom business cards.",
        features: ["Matte or glossy finish", "Custom sizes available", "Eco-friendly paper options"],
        specifications: {
            Material: "350gsm card stock",
            Finish: "Matte / Gloss",
            "Printing Sides": "Single or Double",
        },
        variations: [
            { name: "Matte Finish", price: "$25", image: "/images/variation-matte.png" },
            { name: "Gloss Finish", price: "$30", image: "/images/variation-gloss.png" },
        ],
        faqs: [
            { question: "Can I print on both sides?", answer: "Yes, we offer both single and double-sided printing." },
            { question: "What file format should I upload?", answer: "PDF, AI, or high-res PNG/JPG recommended." },
        ],
    },
    {
        slug: "letterheads",
        name: "Professional Letterheads",
        sectionId: "print-marketing",
        price: "Starting from $35",
        rating: 4.8,
        reviews: 142,
        images: ["/images/letterheads1.png", "/images/letterheads2.png"],
        description: "Professional letterheads that enhance your business correspondence and brand image.",
        features: ["High-quality paper stock", "Custom branding options", "Multiple sizes available"],
        specifications: {
            Material: "Premium paper stock",
            Finish: "Matte / Gloss",
            "Printing Sides": "Single or Double",
        },
        variations: [
            { name: "Standard Letterhead", price: "$35", image: "/images/letterhead-standard.png" },
            { name: "Premium Letterhead", price: "$45", image: "/images/letterhead-premium.png" },
        ],
        faqs: [
            { question: "Can I customize the design?", answer: "Yes, we offer full customization services for your letterhead design." },
            { question: "What paper weights are available?", answer: "We offer various paper weights from 80gsm to 300gsm." },
        ],
    },
    {
        slug: "envelopes",
        name: "Custom Envelopes",
        sectionId: "print-marketing",
        price: "Starting from $20",
        rating: 4.7,
        reviews: 98,
        images: ["/images/envelopes1.png", "/images/envelopes2.png"],
        description: "Custom printed envelopes to match your letterheads and complete your stationery set.",
        features: ["Various sizes available", "Custom printing options", "High-quality materials"],
        specifications: {
            Material: "Paper / Card stock",
            Sizes: "Standard / Custom",
            Printing: "Full color",
        },
        variations: [
            { name: "Standard Envelopes", price: "$20", image: "/images/envelope-standard.png" },
            { name: "Window Envelopes", price: "$25", image: "/images/envelope-window.png" },
        ],
        faqs: [
            { question: "Can I print on the flaps?", answer: "Yes, we can print on both front and back of envelopes." },
            { question: "What sizes are available?", answer: "Standard business sizes plus custom dimensions available." },
        ],
    },
    {
        slug: "folders",
        name: "Presentation Folders",
        sectionId: "print-marketing",
        price: "Starting from $45",
        rating: 4.8,
        reviews: 134,
        images: ["/images/folders1.png", "/images/folders2.png"],
        description: "Professional presentation folders for meetings, proposals, and marketing materials.",
        features: ["Durable construction", "Custom pockets", "Professional finish"],
        specifications: {
            Material: "Card stock / Premium paper",
            Finish: "Matte / Gloss",
            Pockets: "Custom options",
        },
        variations: [
            { name: "Standard Folder", price: "$45", image: "/images/folder-standard.png" },
            { name: "Premium Folder", price: "$65", image: "/images/folder-premium.png" },
        ],
        faqs: [
            { question: "Can I add custom pockets?", answer: "Yes, we can add various pocket configurations to suit your needs." },
            { question: "What materials are available?", answer: "We offer various card stocks and premium paper options." },
        ],
    },
    {
        slug: "notepads",
        name: "Custom Notepads",
        sectionId: "print-marketing",
        price: "Starting from $15",
        rating: 4.6,
        reviews: 87,
        images: ["/images/notepads1.png", "/images/notepads2.png"],
        description: "Branded notepads for office use and promotional purposes.",
        features: ["Custom branding", "Various sizes", "Perforated sheets"],
        specifications: {
            Material: "Paper",
            Size: "Various options",
            Sheets: "50-100 sheets",
        },
        variations: [
            { name: "Standard Notepad", price: "$15", image: "/images/notepad-standard.png" },
            { name: "Premium Notepad", price: "$25", image: "/images/notepad-premium.png" },
        ],
        faqs: [
            { question: "Can I customize the header?", answer: "Yes, we can add your logo and contact information." },
            { question: "What binding options are available?", answer: "Spiral, glue, or staple binding options available." },
        ],
    },
    {
        slug: "notebook-journal",
        name: "Custom Notebooks & Journals",
        sectionId: "print-marketing",
        price: "Starting from $25",
        rating: 4.7,
        reviews: 156,
        images: ["/images/notebooks1.png", "/images/notebooks2.png"],
        description: "Premium custom notebooks and journals for corporate gifting and branding.",
        features: ["Premium binding", "Custom covers", "High-quality paper"],
        specifications: {
            Material: "Premium paper",
            Binding: "Spiral / Perfect bound",
            Pages: "Custom options",
        },
        variations: [
            { name: "Spiral Notebook", price: "$25", image: "/images/notebook-spiral.png" },
            { name: "Perfect Bound Journal", price: "$35", image: "/images/journal-perfect.png" },
        ],
        faqs: [
            { question: "Can I choose the paper type?", answer: "Yes, we offer various paper types including lined, blank, and dotted." },
            { question: "What cover materials are available?", answer: "Various cover materials including leather, vinyl, and paper available." },
        ],
    },
    {
        slug: "brochures",
        name: "Custom Brochures",
        sectionId: "print-marketing",
        price: "Starting from $45",
        rating: 4.8,
        reviews: 189,
        images: ["/images/brochures1.png", "/images/brochures2.png"],
        description: "Professional brochures for marketing and promotional purposes.",
        features: ["High-quality printing", "Various folds", "Custom designs"],
        specifications: {
            Material: "Premium paper",
            Folding: "Various options",
            Printing: "Full color",
        },
        variations: [
            { name: "Bi-fold Brochure", price: "$45", image: "/images/brochure-bifold.png" },
            { name: "Tri-fold Brochure", price: "$55", image: "/images/brochure-trifold.png" },
        ],
        faqs: [
            { question: "What folding options are available?", answer: "Bi-fold, tri-fold, gate fold, and custom folding options available." },
            { question: "Can I get custom designs?", answer: "Yes, we offer custom design services for your brochures." },
        ],
    },
    {
        slug: "flyers",
        name: "Promotional Flyers",
        sectionId: "print-marketing",
        price: "Starting from $15",
        rating: 4.7,
        reviews: 210,
        images: ["/images/flyer1.png", "/images/flyer2.png"],
        description: "Affordable flyers to promote your events and campaigns.",
        features: ["Multiple sizes", "Glossy/matte paper", "Bulk discounts"],
        specifications: { Sizes: "A4 / A5 / Custom", Print: "Full color", Quantity: "50+" },
        variations: [{ name: "A5 Flyers", price: "$15", image: "/images/flyer-a5.png" }],
        faqs: [{ question: "Do you offer design services?", answer: "Yes, design assistance is available." }],
    },
    {
        slug: "booklets-catalogues",
        name: "Booklets & Catalogues",
        sectionId: "print-marketing",
        price: "Starting from $85",
        rating: 4.8,
        reviews: 156,
        images: ["/images/booklets1.png", "/images/booklets2.png"],
        description: "Professional booklets and catalogues for product showcases and marketing.",
        features: ["High-quality binding", "Full-color printing", "Custom sizes"],
        specifications: {
            Material: "Premium paper",
            Binding: "Perfect bound / Saddle stitched",
            Pages: "8-200 pages",
        },
        variations: [
            { name: "Saddle Stitched Booklet", price: "$85", image: "/images/booklet-saddle.png" },
            { name: "Perfect Bound Catalogue", price: "$125", image: "/images/catalogue-perfect.png" },
        ],
        faqs: [
            { question: "What's the minimum page count?", answer: "Minimum 8 pages for booklets and catalogues." },
            { question: "Can I add custom covers?", answer: "Yes, we can create custom front and back covers." },
        ],
    },
    {
        slug: "self-ink-stamps",
        name: "Self Ink Stamps",
        sectionId: "print-marketing",
        price: "Starting from $25",
        rating: 4.6,
        reviews: 98,
        images: ["/images/self-ink-stamps1.png", "/images/self-ink-stamps2.png"],
        description: "Convenient self-inking stamps for office use and business applications.",
        features: ["Self-inking mechanism", "Various sizes", "Custom designs"],
        specifications: {
            Material: "Rubber / Polymer",
            Ink: "Blue / Black / Red",
            Size: "Various options",
        },
        variations: [
            { name: "Standard Self Ink Stamp", price: "$25", image: "/images/stamp-standard.png" },
            { name: "Premium Self Ink Stamp", price: "$35", image: "/images/stamp-premium.png" },
        ],
        faqs: [
            { question: "How long does the ink last?", answer: "Ink lasts for approximately 10,000 impressions." },
            { question: "Can I change the ink color?", answer: "Yes, ink pads are replaceable in various colors." },
        ],
    },
    {
        slug: "wax-seal",
        name: "Wax Seal",
        sectionId: "print-marketing",
        price: "Starting from $45",
        rating: 4.9,
        reviews: 134,
        images: ["/images/wax-seal1.png", "/images/wax-seal2.png"],
        description: "Traditional wax seals for formal documents and special occasions.",
        features: ["Traditional design", "Custom logos", "Premium wax"],
        specifications: {
            Material: "Metal / Brass",
            Wax: "Traditional / Colored",
            Size: "Various diameters",
        },
        variations: [
            { name: "Standard Wax Seal", price: "$45", image: "/images/wax-seal-standard.png" },
            { name: "Premium Wax Seal", price: "$65", image: "/images/wax-seal-premium.png" },
        ],
        faqs: [
            { question: "What wax colors are available?", answer: "Traditional red, plus various colors including gold and silver." },
            { question: "Can I use my own design?", answer: "Yes, we can create custom designs from your artwork." },
        ],
    },
    {
        slug: "embossing-seal",
        name: "Embossing Seal",
        sectionId: "print-marketing",
        price: "Starting from $35",
        rating: 4.7,
        reviews: 89,
        images: ["/images/embossing-seal1.png", "/images/embossing-seal2.png"],
        description: "Professional embossing seals for official documents and certificates.",
        features: ["Raised impression", "Professional finish", "Custom designs"],
        specifications: {
            Material: "Metal / Steel",
            Size: "Various diameters",
            Design: "Custom options",
        },
        variations: [
            { name: "Standard Embossing Seal", price: "$35", image: "/images/embossing-standard.png" },
            { name: "Premium Embossing Seal", price: "$55", image: "/images/embossing-premium.png" },
        ],
        faqs: [
            { question: "What materials can be embossed?", answer: "Paper, card stock, leather, and other soft materials." },
            { question: "Can I get a custom design?", answer: "Yes, we can create custom embossing designs from your artwork." },
        ],
    },
    {
        slug: "invoice-books",
        name: "Invoice Books",
        sectionId: "print-marketing",
        price: "Starting from $25",
        rating: 4.5,
        reviews: 67,
        images: ["/images/invoice-books1.png", "/images/invoice-books2.png"],
        description: "Professional invoice books for business transactions and record keeping.",
        features: ["Carbon copies", "Custom layouts", "Durable binding"],
        specifications: {
            Material: "Premium paper",
            Copies: "Duplicate / Triplicate",
            Binding: "Glue / Spiral",
        },
        variations: [
            { name: "Duplicate Invoice Book", price: "$25", image: "/images/invoice-duplicate.png" },
            { name: "Triplicate Invoice Book", price: "$35", image: "/images/invoice-triplicate.png" },
        ],
        faqs: [
            { question: "Can I customize the layout?", answer: "Yes, we can create custom invoice layouts for your business." },
            { question: "What's the minimum order quantity?", answer: "Minimum 10 books per order." },
        ],
    },
    {
        slug: "receipt-vouchers",
        name: "Receipt Vouchers",
        sectionId: "print-marketing",
        price: "Starting from $20",
        rating: 4.4,
        reviews: 45,
        images: ["/images/receipt-vouchers1.png", "/images/receipt-vouchers2.png"],
        description: "Professional receipt vouchers for transactions and record keeping.",
        features: ["Carbon copies", "Sequential numbering", "Custom designs"],
        specifications: {
            Material: "Premium paper",
            Copies: "Single / Duplicate",
            Numbering: "Sequential",
        },
        variations: [
            { name: "Standard Receipt Vouchers", price: "$20", image: "/images/receipt-standard.png" },
            { name: "Premium Receipt Vouchers", price: "$30", image: "/images/receipt-premium.png" },
        ],
        faqs: [
            { question: "Can I add sequential numbering?", answer: "Yes, we can add sequential numbering to all vouchers." },
            { question: "What sizes are available?", answer: "Various standard sizes plus custom dimensions available." },
        ],
    },
    {
        slug: "banners",
        name: "Large Format Banners",
        sectionId: "print-marketing",
        price: "Starting from $45",
        rating: 4.8,
        reviews: 198,
        images: ["/images/banners1.png", "/images/banners2.png"],
        description: "High-quality large format banners for events, advertising, and promotions.",
        features: ["Weather resistant", "High resolution printing", "Various sizes"],
        specifications: {
            Material: "PVC / Vinyl",
            Size: "Custom dimensions",
            Printing: "Full color",
        },
        variations: [
            { name: "Standard Banner", price: "$45", image: "/images/banner-standard.png" },
            { name: "Premium Banner", price: "$65", image: "/images/banner-premium.png" },
        ],
        faqs: [
            { question: "What's the maximum size?", answer: "We can print banners up to 3 meters wide and any length." },
            { question: "Are banners weather resistant?", answer: "Yes, our banners are designed for outdoor use." },
        ],
    },
    {
        slug: "posters",
        name: "Large Format Posters",
        sectionId: "print-marketing",
        price: "Starting from $35",
        rating: 4.7,
        reviews: 167,
        images: ["/images/posters1.png", "/images/posters2.png"],
        description: "High-quality posters for advertising, events, and promotional purposes.",
        features: ["High resolution", "Various sizes", "Professional finish"],
        specifications: {
            Material: "Paper / Vinyl",
            Size: "A0 / A1 / Custom",
            Printing: "Full color",
        },
        variations: [
            { name: "Paper Poster", price: "$35", image: "/images/poster-paper.png" },
            { name: "Vinyl Poster", price: "$55", image: "/images/poster-vinyl.png" },
        ],
        faqs: [
            { question: "What paper weights are available?", answer: "Various weights from 150gsm to 300gsm available." },
            { question: "Can I get laminated posters?", answer: "Yes, lamination options available for durability." },
        ],
    },
    {
        slug: "billboards",
        name: "Billboard Advertising",
        sectionId: "print-marketing",
        price: "Starting from $150",
        rating: 4.9,
        reviews: 89,
        images: ["/images/billboards1.png", "/images/billboards2.png"],
        description: "Large format billboard printing for outdoor advertising campaigns.",
        features: ["Massive size", "Weather resistant", "High visibility"],
        specifications: {
            Material: "Heavy-duty vinyl",
            Size: "Large format",
            Installation: "Professional service",
        },
        variations: [
            { name: "Standard Billboard", price: "$150", image: "/images/billboard-standard.png" },
            { name: "Premium Billboard", price: "$250", image: "/images/billboard-premium.png" },
        ],
        faqs: [
            { question: "Do you provide installation?", answer: "Yes, we offer professional installation services." },
            { question: "How long do billboards last?", answer: "Our billboards can last 12-18 months outdoors." },
        ],
    },
    {
        slug: "vehicle-wraps",
        name: "Vehicle Wraps",
        sectionId: "print-marketing",
        price: "Starting from $299",
        rating: 4.8,
        reviews: 134,
        images: ["/images/vehicle-wraps1.png", "/images/vehicle-wraps2.png"],
        description: "Professional vehicle wraps for mobile advertising and branding.",
        features: ["Full vehicle coverage", "Weather resistant", "Professional installation"],
        specifications: {
            Material: "Premium vinyl",
            Installation: "Professional service",
            Warranty: "3 years",
        },
        variations: [
            { name: "Partial Vehicle Wrap", price: "$299", image: "/images/vehicle-partial.png" },
            { name: "Full Vehicle Wrap", price: "$599", image: "/images/vehicle-full.png" },
        ],
        faqs: [
            { question: "How long does installation take?", answer: "Installation typically takes 1-2 days depending on vehicle size." },
            { question: "Are wraps removable?", answer: "Yes, wraps can be removed without damaging the vehicle paint." },
        ],
    },
    {
        slug: "window-graphics",
        name: "Window Graphics",
        sectionId: "print-marketing",
        price: "Starting from $25",
        rating: 4.7,
        reviews: 156,
        images: ["/images/window-graphics1.png", "/images/window-graphics2.png"],
        description: "Professional window graphics for branding and decoration.",
        features: ["Weather resistant", "Custom designs", "Professional finish"],
        specifications: { Material: "Vinyl", Printing: "Full color", Installation: "Professional" },
        variations: [
            { name: "Window Lettering", price: "$25", image: "/images/window-lettering.png" },
            { name: "Window Graphics", price: "$35", image: "/images/window-graphics-variation.png" }
        ],
        faqs: [
            { question: "How long do they last?", answer: "Window graphics can last 3-5 years with proper care." },
            { question: "Can they be applied to any window?", answer: "Yes, suitable for most glass surfaces." }
        ],
    },
    {
        slug: "wall-murals",
        name: "Wall Murals",
        sectionId: "print-marketing",
        price: "Starting from $30/sqft",
        rating: 4.9,
        reviews: 88,
        images: ["/images/mural1.png", "/images/mural2.png"],
        description: "Transform workspaces with creative wall murals.",
        features: ["Custom sizes", "Durable vinyl", "Easy to clean"],
        specifications: { Material: "Vinyl", Finish: "Matte/Gloss", Installation: "Available" },
        variations: [{ name: "Abstract Design", price: "$30/sqft", image: "/images/mural-abstract.png" }],
        faqs: [{ question: "Do you offer installation?", answer: "Yes, on-site installation available." }],
    },
    {
        slug: "cd-dvd-printing",
        name: "CD / DVD Printing",
        sectionId: "print-marketing",
        price: "Starting from $35",
        rating: 4.5,
        reviews: 67,
        images: ["/images/cd-dvd-printing1.png", "/images/cd-dvd-printing2.png"],
        description: "Professional CD and DVD printing services for music, software, and data discs.",
        features: ["High-quality printing", "Various formats", "Custom designs"],
        specifications: {
            Formats: "CD / DVD",
            Printing: "Full color",
            Quantity: "Bulk available",
        },
        variations: [
            { name: "CD Printing", price: "$35", image: "/images/cd-printing.png" },
            { name: "DVD Printing", price: "$45", image: "/images/dvd-printing.png" },
        ],
        faqs: [
            { question: "What formats are supported?", answer: "CD-R, CD-RW, DVD-R, DVD+R, and Blu-ray formats available." },
            { question: "Can I print on both sides?", answer: "Yes, we offer single and double-sided printing options." },
        ],
    },
    {
        slug: "cd-dvd-covers",
        name: "CD / DVD Covers",
        sectionId: "print-marketing",
        price: "Starting from $25",
        rating: 4.4,
        reviews: 45,
        images: ["/images/cd-dvd-covers1.png", "/images/cd-dvd-covers2.png"],
        description: "Professional CD and DVD cover printing for packaging and presentation.",
        features: ["Professional finish", "Custom designs", "Various styles"],
        specifications: {
            Material: "Premium paper",
            Size: "Standard formats",
            Printing: "Full color",
        },
        variations: [
            { name: "Standard CD Cover", price: "$25", image: "/images/cd-cover-standard.png" },
            { name: "Premium DVD Cover", price: "$35", image: "/images/dvd-cover-premium.png" },
        ],
        faqs: [
            { question: "What cover styles are available?", answer: "Jewel case inserts, digipak, and custom cover designs available." },
            { question: "Can I get custom artwork?", answer: "Yes, we can create custom artwork for your CD/DVD covers." },
        ],
    },
    {
        slug: "die-cut-stickers",
        name: "Die Cut Stickers",
        sectionId: "print-marketing",
        price: "Starting from $20",
        rating: 4.7,
        reviews: 134,
        images: ["/images/die-cut-stickers1.png", "/images/die-cut-stickers2.png"],
        description: "Custom die cut stickers with precise cutting and professional finish.",
        features: ["Precise cutting", "Custom shapes", "Professional finish"],
        specifications: {
            Material: "Vinyl / Paper",
            Cutting: "Die cut",
            Adhesive: "Permanent",
        },
        variations: [
            { name: "Vinyl Die Cut", price: "$20", image: "/images/vinyl-die-cut.png" },
            { name: "Paper Die Cut", price: "$15", image: "/images/paper-die-cut.png" },
        ],
        faqs: [
            { question: "What shapes can be cut?", answer: "Any custom shape can be die cut from your design." },
            { question: "Is it weather resistant?", answer: "Vinyl die cut stickers are weather resistant and durable." },
        ],
    },
    {
        slug: "print-cut-stickers",
        name: "Print & Cut Stickers",
        sectionId: "print-marketing",
        price: "Starting from $25",
        rating: 4.6,
        reviews: 98,
        images: ["/images/print-cut-stickers1.png", "/images/print-cut-stickers2.png"],
        description: "High-quality print and cut stickers with custom designs and precise cutting.",
        features: ["Full-color printing", "Precise cutting", "Custom designs"],
        specifications: {
            Material: "Vinyl",
            Printing: "Full color",
            Cutting: "Precise cut",
        },
        variations: [
            { name: "Standard Print & Cut", price: "$25", image: "/images/print-cut-standard.png" },
            { name: "Premium Print & Cut", price: "$35", image: "/images/print-cut-premium.png" },
        ],
        faqs: [
            { question: "What printing method is used?", answer: "We use high-quality digital printing for vibrant colors." },
            { question: "Can I get custom shapes?", answer: "Yes, we can cut any custom shape from your design." },
        ],
    },
    {
        slug: "paper-sticker-gloss-matt",
        name: "Paper Sticker Gloss / Matt",
        sectionId: "print-marketing",
        price: "Starting from $15",
        rating: 4.5,
        reviews: 89,
        images: ["/images/paper-sticker-gloss1.png", "/images/paper-sticker-gloss2.png"],
        description: "Paper stickers available in both gloss and matt finishes for different applications.",
        features: ["Gloss and matt options", "Custom designs", "High-quality paper"],
        specifications: {
            Material: "Premium paper",
            Finish: "Gloss / Matt",
            Printing: "Full color",
        },
        variations: [
            { name: "Gloss Paper Sticker", price: "$15", image: "/images/gloss-paper-sticker.png" },
            { name: "Matt Paper Sticker", price: "$18", image: "/images/matt-paper-sticker.png" },
        ],
        faqs: [
            { question: "What's the difference between gloss and matt?", answer: "Gloss provides a shiny finish while matt offers a non-reflective surface." },
            { question: "Which finish is more durable?", answer: "Both finishes are durable, but gloss tends to be more resistant to moisture." },
        ],
    },
    {
        slug: "transparent-stickers",
        name: "Transparent Stickers",
        sectionId: "print-marketing",
        price: "Starting from $25",
        rating: 4.8,
        reviews: 156,
        images: ["/images/transparent-stickers1.png", "/images/transparent-stickers2.png"],
        description: "Clear transparent stickers that blend seamlessly with any background.",
        features: ["Transparent background", "Professional appearance", "Custom designs"],
        specifications: {
            Material: "Clear vinyl",
            Finish: "Transparent",
            Adhesive: "Strong",
        },
        variations: [
            { name: "Standard Transparent", price: "$25", image: "/images/transparent-standard.png" },
            { name: "Premium Transparent", price: "$35", image: "/images/transparent-premium.png" },
        ],
        faqs: [
            { question: "Can transparent stickers be applied to any surface?", answer: "Yes, they work well on glass, plastic, and other smooth surfaces." },
            { question: "Are they removable?", answer: "Yes, designed for easy removal without leaving residue." },
        ],
    },
    {
        slug: "pvc-stickers-white",
        name: "PVC Stickers White",
        sectionId: "print-marketing",
        price: "Starting from $30",
        rating: 4.7,
        reviews: 112,
        images: ["/images/pvc-stickers-white1.png", "/images/pvc-stickers-white2.png"],
        description: "Durable white PVC stickers for outdoor and industrial applications.",
        features: ["Weather resistant", "Durable material", "White background"],
        specifications: {
            Material: "White PVC",
            Durability: "Outdoor grade",
            Adhesive: "Permanent",
        },
        variations: [
            { name: "Standard White PVC", price: "$30", image: "/images/white-pvc-standard.png" },
            { name: "Premium White PVC", price: "$40", image: "/images/white-pvc-premium.png" },
        ],
        faqs: [
            { question: "How weather resistant are they?", answer: "PVC stickers can withstand outdoor conditions for 3-5 years." },
            { question: "Can they be applied to curved surfaces?", answer: "Yes, PVC material is flexible and conforms to curved surfaces." },
        ],
    },
    {
        slug: "epoxy-stickers",
        name: "Epoxy Stickers",
        sectionId: "print-marketing",
        price: "Starting from $35",
        rating: 4.9,
        reviews: 178,
        images: ["/images/epoxy-stickers1.png", "/images/epoxy-stickers2.png"],
        description: "Premium epoxy stickers with a raised, glossy finish for maximum durability.",
        features: ["Raised finish", "High durability", "Professional appearance"],
        specifications: {
            Material: "Epoxy coated",
            Finish: "Raised glossy",
            Durability: "High",
        },
        variations: [
            { name: "Standard Epoxy", price: "$35", image: "/images/epoxy-standard.png" },
            { name: "Premium Epoxy", price: "$50", image: "/images/epoxy-premium.png" },
        ],
        faqs: [
            { question: "What makes epoxy stickers special?", answer: "Epoxy coating provides a raised, glossy finish and exceptional durability." },
            { question: "How long do they last?", answer: "Epoxy stickers can last 5-7 years in outdoor conditions." },
        ],
    },
    {
        slug: "windshield-stickers",
        name: "Windshield Stickers",
        sectionId: "print-marketing",
        price: "Starting from $40",
        rating: 4.8,
        reviews: 145,
        images: ["/images/windshield-stickers1.png", "/images/windshield-stickers2.png"],
        description: "Specialized stickers designed for vehicle windshields and automotive applications.",
        features: ["Automotive grade", "Weather resistant", "Custom designs"],
        specifications: {
            Material: "Automotive vinyl",
            Application: "Windshield",
            Durability: "Vehicle grade",
        },
        variations: [
            { name: "Standard Windshield", price: "$40", image: "/images/windshield-standard.png" },
            { name: "Premium Windshield", price: "$55", image: "/images/windshield-premium.png" },
        ],
        faqs: [
            { question: "Are they safe for vehicle use?", answer: "Yes, specifically designed for automotive applications and safety standards." },
            { question: "Can they be removed without damage?", answer: "Yes, designed for easy removal without damaging the windshield." },
        ],
    },
    // --- MISSING PRINT & MARKETING PRODUCTS ---
    {
        slug: "binding",
        name: "Document Binding",
        sectionId: "print-marketing",
        price: "Starting from $15",
        rating: 4.5,
        reviews: 89,
        images: ["/images/binding1.png", "/images/binding2.png"],
        description: "Professional document binding services for reports and presentations.",
        features: ["Various binding methods", "Professional finish", "Custom covers"],
        specifications: { Method: "Spiral/Perfect bound", Cover: "Custom options", Size: "Various" },
        variations: [
            { name: "Spiral Binding", price: "$15", image: "/images/spiral-binding.png" },
            { name: "Perfect Binding", price: "$25", image: "/images/perfect-binding.png" },
        ],
        faqs: [
            { question: "What binding methods are available?", answer: "Spiral binding, perfect binding, and saddle stitching available." },
            { question: "Can I get custom covers?", answer: "Yes, we offer custom cover designs for your documents." },
        ],
    },
    {
        slug: "thank-you-cards",
        name: "Thank You Cards",
        sectionId: "print-marketing",
        price: "Starting from $20",
        rating: 4.6,
        reviews: 67,
        images: ["/images/thank-you-cards1.png", "/images/thank-you-cards2.png"],
        description: "Elegant thank you cards for business and personal use.",
        features: ["Premium paper", "Custom designs", "Various sizes"],
        specifications: { Material: "Premium card stock", Size: "Standard sizes", Printing: "Full color" },
        variations: [
            { name: "Standard Thank You Cards", price: "$20", image: "/images/thank-you-standard.png" },
            { name: "Premium Thank You Cards", price: "$35", image: "/images/thank-you-premium.png" },
        ],
        faqs: [
            { question: "What paper weights are available?", answer: "Various weights from 200gsm to 350gsm available." },
            { question: "Can I customize the message?", answer: "Yes, we can add custom messages and designs." },
        ],
    },
    {
        slug: "certificates",
        name: "Custom Certificates",
        sectionId: "print-marketing",
        price: "Starting from $25",
        rating: 4.7,
        reviews: 112,
        images: ["/images/certificates1.png", "/images/certificates2.png"],
        description: "Professional certificates for awards, achievements, and recognition.",
        features: ["Premium paper", "Custom designs", "Embossed seals"],
        specifications: { Material: "Premium paper", Design: "Custom", Seal: "Embossed optional" },
        variations: [
            { name: "Standard Certificate", price: "$25", image: "/images/certificate-standard.png" },
            { name: "Premium Certificate", price: "$45", image: "/images/certificate-premium.png" },
        ],
        faqs: [
            { question: "Can I add embossed seals?", answer: "Yes, we can add embossed seals for official certificates." },
            { question: "What information can be customized?", answer: "All text, dates, names, and designs can be customized." },
        ],
    },
    {
        slug: "calendars",
        name: "Custom Calendars",
        sectionId: "print-marketing",
        price: "Starting from $35",
        rating: 4.8,
        reviews: 156,
        images: ["/images/calendars1.png", "/images/calendars2.png"],
        description: "Custom calendars for promotional and corporate use.",
        features: ["Custom designs", "Various formats", "High-quality printing"],
        specifications: { Format: "Wall/Desk", Size: "Various", Printing: "Full color" },
        variations: [
            { name: "Wall Calendar", price: "$35", image: "/images/wall-calendar.png" },
            { name: "Desk Calendar", price: "$25", image: "/images/desk-calendar.png" },
        ],
        faqs: [
            { question: "What calendar formats are available?", answer: "Wall calendars, desk calendars, and pocket calendars available." },
            { question: "Can I add corporate branding?", answer: "Yes, we can incorporate your logo and branding throughout." },
        ],
    },
    {
        slug: "hang-tags",
        name: "Hang Tags",
        sectionId: "print-marketing",
        price: "Starting from $15",
        rating: 4.4,
        reviews: 78,
        images: ["/images/hang-tags1.png", "/images/hang-tags2.png"],
        description: "Professional hang tags for products and merchandise.",
        features: ["Durable material", "Custom designs", "Various shapes"],
        specifications: { Material: "Card stock", Shape: "Custom", Hole: "Reinforced" },
        variations: [
            { name: "Standard Hang Tags", price: "$15", image: "/images/hang-tag-standard.png" },
            { name: "Premium Hang Tags", price: "$25", image: "/images/hang-tag-premium.png" },
        ],
        faqs: [
            { question: "What shapes are available?", answer: "Various shapes including rectangular, round, and custom shapes." },
            { question: "Are the holes reinforced?", answer: "Yes, all hang tags have reinforced holes for durability." },
        ],
    },
    {
        slug: "stencil-stickers",
        name: "Stencil Stickers",
        sectionId: "print-marketing",
        price: "Starting from $20",
        rating: 4.5,
        reviews: 89,
        images: ["/images/stencil-stickers1.png", "/images/stencil-stickers2.png"],
        description: "Stencil-style stickers for decorative and functional use.",
        features: ["Stencil design", "Easy application", "Custom shapes"],
        specifications: { Material: "Vinyl", Design: "Stencil", Application: "Easy peel" },
        variations: [
            { name: "Standard Stencil", price: "$20", image: "/images/stencil-standard.png" },
            { name: "Premium Stencil", price: "$30", image: "/images/stencil-premium.png" },
        ],
        faqs: [
            { question: "What is a stencil design?", answer: "Stencil designs have cut-out patterns that create visual effects." },
            { question: "Can I create custom stencil designs?", answer: "Yes, we can create custom stencil designs from your artwork." },
        ],
    },
    {
        slug: "foil-stickers",
        name: "Foil Stickers",
        sectionId: "print-marketing",
        price: "Starting from $25",
        rating: 4.7,
        reviews: 134,
        images: ["/images/foil-stickers1.png", "/images/foil-stickers2.png"],
        description: "Premium foil stickers with metallic finish for luxury branding.",
        features: ["Metallic finish", "Premium appearance", "Custom designs"],
        specifications: { Material: "Foil vinyl", Finish: "Metallic", Quality: "Premium" },
        variations: [
            { name: "Gold Foil Stickers", price: "$25", image: "/images/gold-foil.png" },
            { name: "Silver Foil Stickers", price: "$25", image: "/images/silver-foil.png" },
        ],
        faqs: [
            { question: "What foil colors are available?", answer: "Gold, silver, copper, and various metallic colors available." },
            { question: "Are foil stickers durable?", answer: "Yes, foil stickers are highly durable and weather resistant." },
        ],
    },
    {
        slug: "metal-stickers",
        name: "Metal Stickers",
        sectionId: "print-marketing",
        price: "Starting from $35",
        rating: 4.8,
        reviews: 98,
        images: ["/images/metal-stickers1.png", "/images/metal-stickers2.png"],
        description: "Durable metal stickers for industrial and outdoor applications.",
        features: ["Metal construction", "Weather resistant", "Long-lasting"],
        specifications: { Material: "Aluminum/Steel", Durability: "High", Application: "Outdoor" },
        variations: [
            { name: "Aluminum Stickers", price: "$35", image: "/images/aluminum-stickers.png" },
            { name: "Steel Stickers", price: "$45", image: "/images/steel-stickers.png" },
        ],
        faqs: [
            { question: "What metals are available?", answer: "Aluminum and steel options available in various finishes." },
            { question: "How weather resistant are they?", answer: "Metal stickers are highly weather resistant and can last years outdoors." },
        ],
    },
    {
        slug: "embossing-seal-stickers",
        name: "Embossing Seal Stickers",
        sectionId: "print-marketing",
        price: "Starting from $30",
        rating: 4.6,
        reviews: 76,
        images: ["/images/embossing-seal-stickers1.png", "/images/embossing-seal-stickers2.png"],
        description: "Embossed stickers with raised seal design for official use.",
        features: ["Raised design", "Official appearance", "Custom seals"],
        specifications: { Material: "Vinyl", Design: "Embossed", Seal: "Custom" },
        variations: [
            { name: "Standard Embossing Seal", price: "$30", image: "/images/emboss-seal-standard.png" },
            { name: "Premium Embossing Seal", price: "$45", image: "/images/emboss-seal-premium.png" },
        ],
        faqs: [
            { question: "What seal designs are available?", answer: "Various seal designs including circular, oval, and custom shapes." },
            { question: "Can I get custom seal designs?", answer: "Yes, we can create custom seal designs for your organization." },
        ],
    },
    {
        slug: "hologram-stickers",
        name: "Hologram Stickers",
        sectionId: "print-marketing",
        price: "Starting from $40",
        rating: 4.9,
        reviews: 156,
        images: ["/images/hologram-stickers1.png", "/images/hologram-stickers2.png"],
        description: "Security hologram stickers for authentication and branding.",
        features: ["Security features", "Holographic effect", "Anti-counterfeit"],
        specifications: { Material: "Holographic", Security: "High", Effect: "3D" },
        variations: [
            { name: "Standard Hologram", price: "$40", image: "/images/hologram-standard.png" },
            { name: "Premium Hologram", price: "$60", image: "/images/hologram-premium.png" },
        ],
        faqs: [
            { question: "What security features are included?", answer: "Holographic effects, tamper-evident features, and unique serial numbers." },
            { question: "Are they difficult to counterfeit?", answer: "Yes, hologram stickers are extremely difficult to counterfeit." },
        ],
    },
    {
        slug: "kraft-paper-stickers",
        name: "Kraft Paper Stickers",
        sectionId: "print-marketing",
        price: "Starting from $12",
        rating: 4.3,
        reviews: 67,
        images: ["/images/kraft-paper-stickers1.png", "/images/kraft-paper-stickers2.png"],
        description: "Eco-friendly kraft paper stickers for sustainable branding.",
        features: ["Eco-friendly", "Natural appearance", "Biodegradable"],
        specifications: { Material: "Kraft paper", Eco: "Biodegradable", Printing: "Natural" },
        variations: [
            { name: "Standard Kraft Paper", price: "$12", image: "/images/kraft-standard.png" },
            { name: "Premium Kraft Paper", price: "$18", image: "/images/kraft-premium.png" },
        ],
        faqs: [
            { question: "Are kraft paper stickers biodegradable?", answer: "Yes, kraft paper stickers are biodegradable and eco-friendly." },
            { question: "What printing methods are used?", answer: "We use eco-friendly printing methods suitable for kraft paper." },
        ],
    },
    {
        slug: "compliment-slips",
        name: "Compliment Slips",
        sectionId: "print-marketing",
        price: "Starting from $15",
        rating: 4.4,
        reviews: 45,
        images: ["/images/compliment-slips1.png", "/images/compliment-slips2.png"],
        description: "Professional compliment slips for business correspondence.",
        features: ["Professional design", "Matching stationery", "Custom branding"],
        specifications: { Material: "Premium paper", Design: "Professional", Branding: "Custom" },
        variations: [
            { name: "Standard Compliment Slips", price: "$15", image: "/images/compliment-standard.png" },
            { name: "Premium Compliment Slips", price: "$25", image: "/images/compliment-premium.png" },
        ],
        faqs: [
            { question: "Can they match my letterheads?", answer: "Yes, we can design compliment slips to match your letterheads." },
            { question: "What information can be included?", answer: "Company details, contact information, and custom branding elements." },
        ],
    },
    {
        slug: "tickets-coupons",
        name: "Tickets & Coupons",
        sectionId: "print-marketing",
        price: "Starting from $8",
        rating: 4.5,
        reviews: 123,
        images: ["/images/tickets-coupons1.png", "/images/tickets-coupons2.png"],
        description: "Custom tickets and coupons for events and promotions.",
        features: ["Sequential numbering", "Custom designs", "Security features"],
        specifications: { Numbering: "Sequential", Security: "Anti-counterfeit", Design: "Custom" },
        variations: [
            { name: "Event Tickets", price: "$8", image: "/images/event-tickets.png" },
            { name: "Promotional Coupons", price: "$12", image: "/images/promo-coupons.png" },
        ],
        faqs: [
            { question: "Can tickets be sequentially numbered?", answer: "Yes, we can add sequential numbering to all tickets." },
            { question: "What security features are available?", answer: "Holographic elements, special inks, and anti-counterfeit measures." },
        ],
    },
    {
        slug: "scratch-win-coupons",
        name: "Scratch & Win Coupons",
        sectionId: "print-marketing",
        price: "Starting from $20",
        rating: 4.7,
        reviews: 89,
        images: ["/images/scratch-win-coupons1.png", "/images/scratch-win-coupons2.png"],
        description: "Interactive scratch and win coupons for promotional campaigns.",
        features: ["Scratch-off coating", "Interactive design", "Prize options"],
        specifications: { Coating: "Scratch-off", Interaction: "Scratch to reveal", Prizes: "Custom" },
        variations: [
            { name: "Standard Scratch Coupons", price: "$20", image: "/images/scratch-standard.png" },
            { name: "Premium Scratch Coupons", price: "$35", image: "/images/scratch-premium.png" },
        ],
        faqs: [
            { question: "How does the scratch-off coating work?", answer: "Special coating reveals hidden text or images when scratched." },
            { question: "Can I customize the prizes?", answer: "Yes, we can customize prizes, discounts, or messages under the coating." },
        ],
    },
    {
        slug: "tent-cards",
        name: "Tent Cards",
        sectionId: "print-marketing",
        price: "Starting from $12",
        rating: 4.4,
        reviews: 78,
        images: ["/images/tent-cards1.png", "/images/tent-cards2.png"],
        description: "Table tent cards for restaurants, events, and displays.",
        features: ["Self-standing", "Double-sided", "Custom designs"],
        specifications: { Design: "Tent shape", Sides: "Double-sided", Material: "Card stock" },
        variations: [
            { name: "Standard Tent Cards", price: "$12", image: "/images/tent-standard.png" },
            { name: "Premium Tent Cards", price: "$20", image: "/images/tent-premium.png" },
        ],
        faqs: [
            { question: "Are tent cards double-sided?", answer: "Yes, tent cards are printed on both sides for visibility." },
            { question: "What sizes are available?", answer: "Various sizes from small table tents to large display cards." },
        ],
    },
    {
        slug: "car-mat",
        name: "Car Mats",
        sectionId: "print-marketing",
        price: "Starting from $45",
        rating: 4.6,
        reviews: 67,
        images: ["/images/car-mat1.png", "/images/car-mat2.png"],
        description: "Custom car mats with logo printing for promotional use.",
        features: ["Durable material", "Logo printing", "Custom fit"],
        specifications: { Material: "Rubber/Cloth", Printing: "Logo", Fit: "Vehicle specific" },
        variations: [
            { name: "Rubber Car Mats", price: "$45", image: "/images/rubber-car-mat.png" },
            { name: "Cloth Car Mats", price: "$55", image: "/images/cloth-car-mat.png" },
        ],
        faqs: [
            { question: "Are car mats vehicle-specific?", answer: "Yes, we can create mats for specific vehicle models." },
            { question: "What printing methods are used?", answer: "We use durable printing methods suitable for automotive use." },
        ],
    },
    {
        slug: "table-mat",
        name: "Table Mats",
        sectionId: "print-marketing",
        price: "Starting from $18",
        rating: 4.5,
        reviews: 89,
        images: ["/images/table-mat1.png", "/images/table-mat2.png"],
        description: "Custom table mats for restaurants and events.",
        features: ["Easy to clean", "Custom designs", "Durable material"],
        specifications: { Material: "Vinyl/Paper", Cleaning: "Easy", Design: "Custom" },
        variations: [
            { name: "Vinyl Table Mats", price: "$18", image: "/images/vinyl-table-mat.png" },
            { name: "Paper Table Mats", price: "$12", image: "/images/paper-table-mat.png" },
        ],
        faqs: [
            { question: "Are table mats easy to clean?", answer: "Yes, our table mats are designed for easy cleaning and maintenance." },
            { question: "Can I get custom designs?", answer: "Yes, we can create custom designs including logos and promotional content." },
        ],
    },
]
