// /lib/DESCRIPTION.ts

export const categories = {
    "print-marketing": {
        title: "Print & Marketing",
        description: "Professional printing solutions for all your marketing needs",
        products: [
            {
                slug: "business-cards",
                name: "Premium Business Cards",
                price: "Starting from $25",
                image: "/images/business-cards.png",
                rating: 4.9,
                reviews: 156,
                category: "Stationery & Corporate Identity",
            },
            {
                slug: "letterheads",
                name: "Professional Letterheads",
                price: "Starting from $35",
                image: "/images/letterheads.png",
                rating: 4.8,
                reviews: 142,
                category: "Stationery & Corporate Identity",
            },
            {
                slug: "envelopes",
                name: "Custom Envelopes",
                price: "Starting from $20",
                image: "/images/envelopes.png",
                rating: 4.7,
                reviews: 98,
                category: "Stationery & Corporate Identity",
            },
            {
                slug: "folders",
                name: "Presentation Folders",
                price: "Starting from $45",
                image: "/images/folders.png",
                rating: 4.8,
                reviews: 134,
                category: "Stationery & Corporate Identity",
            },
            {
                slug: "notepads",
                name: "Custom Notepads",
                price: "Starting from $15",
                image: "/images/notepads.png",
                rating: 4.6,
                reviews: 87,
                category: "Stationery & Corporate Identity",
            },
            {
                slug: "notebook-journal",
                name: "Custom Notebooks & Journals",
                price: "Starting from $25",
                image: "/images/notebooks.png",
                rating: 4.7,
                reviews: 156,
                category: "Stationery & Corporate Identity",
            },
            {
                slug: "binding",
                name: "Document Binding Services",
                price: "Starting from $10",
                image: "/images/binding.png",
                rating: 4.5,
                reviews: 67,
                category: "Stationery & Corporate Identity",
            },
            {
                slug: "thank-you-cards",
                name: "Thank You Cards",
                price: "Starting from $20",
                image: "/images/thank-you-cards.png",
                rating: 4.8,
                reviews: 89,
                category: "Stationery & Corporate Identity",
            },
            {
                slug: "certificates",
                name: "Custom Certificates",
                price: "Starting from $35",
                image: "/images/certificates.png",
                rating: 4.9,
                reviews: 123,
                category: "Stationery & Corporate Identity",
            },
            {
                slug: "calendars",
                name: "Custom Calendars",
                price: "Starting from $25",
                image: "/images/calendars.png",
                rating: 4.6,
                reviews: 145,
                category: "Stationery & Corporate Identity",
            },
            {
                slug: "hang-tags",
                name: "Hang Tags",
                price: "Starting from $15",
                image: "/images/hang-tags.png",
                rating: 4.5,
                reviews: 78,
                category: "Stationery & Corporate Identity",
            },
            {
                slug: "flyers",
                name: "Promotional Flyers",
                price: "Starting from $15",
                image: "/images/flyers.png",
                rating: 4.7,
                reviews: 210,
                category: "Brochures & Flyers",
            },
            {
                slug: "brochures",
                name: "Custom Brochures",
                price: "Starting from $45",
                image: "/images/brochures.png",
                rating: 4.8,
                reviews: 189,
                category: "Brochures & Flyers",
            },
            {
                slug: "booklets-catalogues",
                name: "Booklets & Catalogues",
                price: "Starting from $85",
                image: "/images/booklets.png",
                rating: 4.8,
                reviews: 156,
                category: "Brochures & Flyers",
            },
            {
                slug: "self-ink-stamps",
                name: "Self Ink Stamps",
                price: "Starting from $25",
                image: "/images/self-ink-stamps.png",
                rating: 4.6,
                reviews: 98,
                category: "Seals",
            },
            {
                slug: "wax-seal",
                name: "Wax Seal",
                price: "Starting from $45",
                image: "/images/wax-seal.png",
                rating: 4.9,
                reviews: 134,
                category: "Seals",
            },
            {
                slug: "embossing-seal",
                name: "Embossing Seal",
                price: "Starting from $35",
                image: "/images/embossing-seal.png",
                rating: 4.7,
                reviews: 89,
                category: "Seals",
            },
            {
                slug: "invoice-books",
                name: "Invoice Books",
                price: "Starting from $25",
                image: "/images/invoice-books.png",
                rating: 4.5,
                reviews: 67,
                category: "Voucher Books",
            },
            {
                slug: "receipt-vouchers",
                name: "Receipt Vouchers",
                price: "Starting from $20",
                image: "/images/receipt-vouchers.png",
                rating: 4.4,
                reviews: 45,
                category: "Voucher Books",
            },
            {
                slug: "banners",
                name: "Large Format Banners",
                price: "Starting from $45",
                image: "/images/banners.png",
                rating: 4.8,
                reviews: 198,
                category: "Large Format Printing",
            },
            {
                slug: "posters",
                name: "Large Format Posters",
                price: "Starting from $35",
                image: "/images/posters.png",
                rating: 4.7,
                reviews: 167,
                category: "Large Format Printing",
            },
            {
                slug: "billboards",
                name: "Billboard Advertising",
                price: "Starting from $150",
                image: "/images/billboards.png",
                rating: 4.9,
                reviews: 89,
                category: "Large Format Printing",
            },
            {
                slug: "vehicle-wraps",
                name: "Vehicle Wraps",
                price: "Starting from $299",
                image: "/images/vehicle-wraps.png",
                rating: 4.8,
                reviews: 134,
                category: "Large Format Printing",
            },
            {
                slug: "window-graphics",
                name: "Window Graphics",
                price: "Starting from $25",
                image: "/images/window-graphics.png",
                rating: 4.7,
                reviews: 156,
                category: "Large Format Printing",
            },
            {
                slug: "wall-murals",
                name: "Wall Murals",
                price: "Starting from $30/sqft",
                image: "/images/wall-murals.png",
                rating: 4.9,
                reviews: 88,
                category: "Large Format Printing",
            },
            {
                slug: "cd-dvd-printing",
                name: "CD / DVD Printing",
                price: "Starting from $35",
                image: "/images/cd-dvd-printing.png",
                rating: 4.5,
                reviews: 67,
                category: "CD / DVD",
            },
            {
                slug: "cd-dvd-covers",
                name: "CD / DVD Covers",
                price: "Starting from $25",
                image: "/images/cd-dvd-covers.png",
                rating: 4.4,
                reviews: 45,
                category: "CD / DVD",
            },
            {
                slug: "die-cut-stickers",
                name: "Die Cut Stickers",
                price: "Starting from $20",
                image: "/images/die-cut-stickers.png",
                rating: 4.7,
                reviews: 134,
                category: "Stickers",
            },
            {
                slug: "print-cut-stickers",
                name: "Print & Cut Stickers",
                price: "Starting from $25",
                image: "/images/print-cut-stickers.png",
                rating: 4.6,
                reviews: 98,
                category: "Stickers",
            },
            {
                slug: "paper-sticker-gloss-matt",
                name: "Paper Sticker Gloss / Matt",
                price: "Starting from $15",
                image: "/images/paper-sticker-gloss.png",
                rating: 4.5,
                reviews: 89,
                category: "Stickers",
            },
            {
                slug: "transparent-stickers",
                name: "Transparent Stickers",
                price: "Starting from $25",
                image: "/images/transparent-stickers.png",
                rating: 4.8,
                reviews: 156,
                category: "Stickers",
            },
            {
                slug: "pvc-stickers-white",
                name: "PVC Stickers White",
                price: "Starting from $30",
                image: "/images/pvc-stickers-white.png",
                rating: 4.7,
                reviews: 112,
                category: "Stickers",
            },
            {
                slug: "epoxy-stickers",
                name: "Epoxy Stickers",
                price: "Starting from $35",
                image: "/images/epoxy-stickers.png",
                rating: 4.9,
                reviews: 178,
                category: "Specialty Stickers",
            },
            {
                slug: "windshield-stickers",
                name: "Windshield Stickers",
                price: "Starting from $40",
                image: "/images/windshield-stickers.png",
                rating: 4.8,
                reviews: 145,
                category: "Stickers",
            },
        ],
    },

    "fashion-textile": {
        title: "Fashion & Textile",
        description: "Custom apparel and textile solutions for your brand",
        products: [
            {
                slug: "scarf",
                name: "Custom Printed Scarves",
                price: "Starting from $25",
                image: "/images/scarf.png",
                rating: 4.8,
                reviews: 156,
                category: "Fashion",
            },
            {
                slug: "sheila",
                name: "Traditional Sheila",
                price: "Starting from $30",
                image: "/images/sheila.png",
                rating: 4.7,
                reviews: 89,
                category: "Fashion",
            },
            {
                slug: "bandana",
                name: "Custom Bandanas",
                price: "Starting from $15",
                image: "/images/bandana.png",
                rating: 4.6,
                reviews: 234,
                category: "Fashion",
            },
            {
                slug: "hair-scarf",
                name: "Hair Scarves",
                price: "Starting from $20",
                image: "/images/hair-scarf.png",
                rating: 4.5,
                reviews: 67,
                category: "Fashion",
            },
            {
                slug: "bag-scarf",
                name: "Bag Scarves",
                price: "Starting from $18",
                image: "/images/bag-scarf.png",
                rating: 4.4,
                reviews: 45,
                category: "Fashion",
            },
            {
                slug: "abaya",
                name: "Custom Abayas",
                price: "Starting from $85",
                image: "/images/abaya.png",
                rating: 4.9,
                reviews: 123,
                category: "Fashion",
            },
            {
                slug: "sarong",
                name: "Custom Sarongs",
                price: "Starting from $35",
                image: "/images/sarong.png",
                rating: 4.6,
                reviews: 78,
                category: "Fashion",
            },
            {
                slug: "beach-shorts",
                name: "Custom Beach Shorts",
                price: "Starting from $25",
                image: "/images/beach-shorts.png",
                rating: 4.5,
                reviews: 56,
                category: "Fashion",
            },
            {
                slug: "pocket-handkerchief",
                name: "Pocket Handkerchiefs",
                price: "Starting from $12",
                image: "/images/pocket-handkerchief.png",
                rating: 4.4,
                reviews: 34,
                category: "Fashion",
            },
            {
                slug: "woven-fabric-labels",
                name: "Woven Fabric Labels",
                price: "Starting from $8",
                image: "/images/woven-fabric-labels.png",
                rating: 4.3,
                reviews: 89,
                category: "Fashion",
            },
            {
                slug: "scrunchie",
                name: "Custom Scrunchies",
                price: "Starting from $5",
                image: "/images/scrunchie.png",
                rating: 4.7,
                reviews: 167,
                category: "Fashion",
            },
        ],
    },

    "office-branding": {
        title: "Office & Store Branding",
        description: "Professional branding solutions for offices and retail spaces",
        products: [
            {
                slug: "reverse-cut-frosted-sticker",
                name: "Reverse Cut Frosted Stickers",
                price: "Starting from $25",
                image: "/images/reverse-cut-frosted.png",
                rating: 4.7,
                reviews: 89,
                category: "Frosted Sticker",
            },
            {
                slug: "standard-cut-frosted-sticker",
                name: "Standard Cut Frosted Stickers",
                price: "Starting from $20",
                image: "/images/standard-cut-frosted.png",
                rating: 4.6,
                reviews: 67,
                category: "Frosted Sticker",
            },
            {
                slug: "printed-frosted-sticker",
                name: "Printed Frosted Stickers",
                price: "Starting from $35",
                image: "/images/printed-frosted.png",
                rating: 4.8,
                reviews: 112,
                category: "Frosted Sticker",
            },
            {
                slug: "blank-frosted-sticker",
                name: "Blank Frosted Stickers",
                price: "Starting from $15",
                image: "/images/blank-frosted.png",
                rating: 4.4,
                reviews: 45,
                category: "Frosted Sticker",
            },
            {
                slug: "window-vinyl-lettering",
                name: "Window Vinyl Lettering",
                price: "Starting from $30",
                image: "/images/window-vinyl-lettering.png",
                rating: 4.7,
                reviews: 134,
                category: "Window Branding",
            },
            {
                slug: "window-graphics",
                name: "Window Graphics",
                price: "Starting from $25",
                image: "/images/window-graphics.png",
                rating: 4.7,
                reviews: 156,
                category: "Window Branding",
            },
            {
                slug: "one-way-vision-sticker",
                name: "One Way Vision Stickers",
                price: "Starting from $40",
                image: "/images/one-way-vision.png",
                rating: 4.8,
                reviews: 98,
                category: "Window Branding",
            },
            {
                slug: "window-films",
                name: "Window Films",
                price: "Starting from $35",
                image: "/images/window-films.png",
                rating: 4.6,
                reviews: 76,
                category: "Window Branding",
            },
            {
                slug: "wall-vinyl-lettering",
                name: "Wall Vinyl Lettering",
                price: "Starting from $25",
                image: "/images/wall-vinyl-lettering.png",
                rating: 4.5,
                reviews: 89,
                category: "Wall Branding",
            },
            {
                slug: "wall-sticker",
                name: "Wall Stickers",
                price: "Starting from $20",
                image: "/images/wall-sticker.png",
                rating: 4.4,
                reviews: 67,
                category: "Wall Branding",
            },
            {
                slug: "wall-decal",
                name: "Wall Decals",
                price: "Starting from $30",
                image: "/images/wall-decal.png",
                rating: 4.6,
                reviews: 78,
                category: "Wall Branding",
            },
            {
                slug: "bedroom-wallpaper",
                name: "Bedroom Wallpaper",
                price: "Starting from $45",
                image: "/images/bedroom-wallpaper.png",
                rating: 4.7,
                reviews: 112,
                category: "Wall Décor",
            },
            {
                slug: "living-room-wallpaper",
                name: "Living Room Wallpaper",
                price: "Starting from $50",
                image: "/images/living-room-wallpaper.png",
                rating: 4.8,
                reviews: 134,
                category: "Wall Décor",
            },
            {
                slug: "wall-frames",
                name: "Wall Frames",
                price: "Starting from $35",
                image: "/images/wall-frames.png",
                rating: 4.8,
                reviews: 203,
                category: "Wall Frames",
            },
        ],
    },

    "signages": {
        title: "Signages",
        description: "Professional signage solutions for businesses and events",
        products: [
            {
                slug: "3d-signage",
                name: "3D Signage",
                price: "Starting from $150",
                image: "/images/3d-signage.png",
                rating: 4.9,
                reviews: 67,
                category: "Sign Board / Signage",
            },
            {
                slug: "name-plates",
                name: "Name Plates",
                price: "Starting from $45",
                image: "/images/name-plates.png",
                rating: 4.7,
                reviews: 134,
                category: "Name Plate",
            },
            {
                slug: "light-box-signages",
                name: "Light Box Signages",
                price: "Starting from $85",
                image: "/images/light-box.png",
                rating: 4.6,
                reviews: 78,
                category: "Light Box Signages",
            },
        ],
    },

    "flags": {
        title: "Flags",
        description: "Custom flags for events, branding, and promotional activities",
        products: [
            {
                slug: "sail-flags",
                name: "Sail Flags",
                price: "Starting from $35",
                image: "/images/sail-flags.png",
                rating: 4.8,
                reviews: 112,
                category: "Event & Branding Flags",
            },
            {
                slug: "tear-drop-flags",
                name: "Tear Drop Flags",
                price: "Starting from $25",
                image: "/images/tear-drop-flags.png",
                rating: 4.7,
                reviews: 89,
                category: "Event & Branding Flags",
            },
            {
                slug: "table-flags",
                name: "Table Flags",
                price: "Starting from $15",
                image: "/images/table-flags.png",
                rating: 4.9,
                reviews: 167,
                category: "Office Flags",
            },
        ],
    },

    "backdrops": {
        title: "Backdrops & Exhibition",
        description: "Professional backdrops and exhibition displays for events and marketing",
        products: [
            {
                slug: "rollup-banners",
                name: "Rollup Banners",
                price: "Starting from $45",
                image: "/images/rollup-banners.png",
                rating: 4.8,
                reviews: 198,
                category: "Standees",
            },
            {
                slug: "fabric-backdrops",
                name: "Fabric Backdrops",
                price: "Starting from $65",
                image: "/images/fabric-backdrops.png",
                rating: 4.9,
                reviews: 145,
                category: "Backdrops",
            },
            {
                slug: "popup-banners",
                name: "Pop Up Banners",
                price: "Starting from $55",
                image: "/images/popup-banners.png",
                rating: 4.7,
                reviews: 123,
                category: "Display Stands",
            },
        ],
    },

    "corporate-gifts": {
        title: "Corporate Gifts & Bags",
        description: "Premium corporate gifts and promotional items for businesses",
        products: [
            {
                slug: "corporate-pens",
                name: "Corporate Pens",
                price: "Starting from $5",
                image: "/images/corporate-pens.png",
                rating: 4.8,
                reviews: 234,
                category: "Office Essentials",
            },
            {
                slug: "promotional-mugs",
                name: "Promotional Mugs",
                price: "Starting from $8",
                image: "/images/promotional-mugs.png",
                rating: 4.7,
                reviews: 187,
                category: "Drinkware",
            },
            {
                slug: "tote-bags",
                name: "Tote Bags",
                price: "Starting from $12",
                image: "/images/tote-bags.png",
                rating: 4.9,
                reviews: 156,
                category: "Shopping/Promotional Bags",
            },
        ],
    },
}
