// /lib/DESCRIPTION.ts

export const categories = {
    "print-marketing": {
        title: "Print & Marketing",
        description: "Professional printing solutions for all your marketing needs",
        products: [
            {
                slug: "business-cards",
                name: "Premium Business Cards",
                price: "Starting from $25",
                image: "/images/business-cards.png",
                rating: 4.9,
                reviews: 156,
                category: "Business Stationery",
            },
            {
                slug: "brochures",
                name: "Custom Brochures",
                price: "Starting from $45",
                image: "/images/brochures.png",
                rating: 4.8,
                reviews: 89,
                category: "Marketing Materials",
            },
            {
                slug: "flyers",
                name: "Promotional Flyers",
                price: "Starting from $15",
                image: "/images/flyers.png",
                rating: 4.7,
                reviews: 234,
                category: "Marketing Materials",
            },
            {
                slug: "catalogs",
                name: "Product Catalogs",
                price: "Starting from $85",
                image: "/images/catalogs.png",
                rating: 4.9,
                reviews: 67,
                category: "Marketing Materials",
            },
        ],
    },

    "fashion-textile": {
        title: "Fashion & Textile",
        description: "Custom apparel and textile solutions for your brand",
        products: [
            {
                slug: "custom-apparel",
                name: "Custom T-Shirts",
                price: "Starting from $12",
                image: "/images/custom-tshirts.png",
                rating: 4.8,
                reviews: 298,
                category: "Apparel",
            },
            {
                slug: "embroidery",
                name: "Embroidered Polo Shirts",
                price: "Starting from $18",
                image: "/images/embroidered-polo.png",
                rating: 4.9,
                reviews: 145,
                category: "Apparel",
            },
            {
                slug: "uniforms",
                name: "Corporate Uniforms",
                price: "Starting from $35",
                image: "/images/corporate-uniforms.png",
                rating: 4.7,
                reviews: 78,
                category: "Apparel",
            },
        ],
    },

    "office-branding": {
        title: "Office & Store Branding",
        description: "Professional branding solutions for offices and retail spaces",
        products: [
            {
                slug: "frosted-stickers",
                name: "Frosted Stickers",
                price: "Starting from $15",
                image: "/images/frosted-stickers.png",
                rating: 4.6,
                reviews: 89,
                category: "Branding",
            },
            {
                slug: "window-graphics",
                name: "Window Graphics",
                price: "Starting from $25",
                image: "/images/window-graphics.png",
                rating: 4.7,
                reviews: 156,
                category: "Branding",
            },
            {
                slug: "wall-frames",
                name: "Wall Frames",
                price: "Starting from $35",
                image: "/images/wall-frames.png",
                rating: 4.8,
                reviews: 203,
                category: "Decor",
            },
        ],
    },

    "signages": {
        title: "Signages",
        description: "Professional signage solutions for businesses and events",
        products: [
            {
                slug: "3d-signage",
                name: "3D Signage",
                price: "Starting from $150",
                image: "/images/3d-signage.png",
                rating: 4.9,
                reviews: 67,
                category: "Signage",
            },
            {
                slug: "name-plates",
                name: "Name Plates",
                price: "Starting from $45",
                image: "/images/name-plates.png",
                rating: 4.7,
                reviews: 134,
                category: "Signage",
            },
            {
                slug: "light-box-signages",
                name: "Light Box Signages",
                price: "Starting from $85",
                image: "/images/light-box.png",
                rating: 4.6,
                reviews: 78,
                category: "Signage",
            },
        ],
    },

    "flags": {
        title: "Flags",
        description: "Custom flags for events, branding, and promotional activities",
        products: [
            {
                slug: "sail-flags",
                name: "Sail Flags",
                price: "Starting from $35",
                image: "/images/sail-flags.png",
                rating: 4.8,
                reviews: 112,
                category: "Event Flags",
            },
            {
                slug: "tear-drop-flags",
                name: "Tear Drop Flags",
                price: "Starting from $25",
                image: "/images/tear-drop-flags.png",
                rating: 4.7,
                reviews: 89,
                category: "Event Flags",
            },
            {
                slug: "table-flags",
                name: "Table Flags",
                price: "Starting from $15",
                image: "/images/table-flags.png",
                rating: 4.9,
                reviews: 167,
                category: "Office Flags",
            },
        ],
    },

    "backdrops": {
        title: "Backdrops & Exhibition",
        description: "Professional backdrops and exhibition displays for events and marketing",
        products: [
            {
                slug: "rollup-banners",
                name: "Rollup Banners",
                price: "Starting from $45",
                image: "/images/rollup-banners.png",
                rating: 4.8,
                reviews: 198,
                category: "Exhibition",
            },
            {
                slug: "fabric-backdrops",
                name: "Fabric Backdrops",
                price: "Starting from $65",
                image: "/images/fabric-backdrops.png",
                rating: 4.9,
                reviews: 145,
                category: "Backdrops",
            },
            {
                slug: "popup-banners",
                name: "Pop Up Banners",
                price: "Starting from $55",
                image: "/images/popup-banners.png",
                rating: 4.7,
                reviews: 123,
                category: "Exhibition",
            },
        ],
    },

    "corporate-gifts": {
        title: "Corporate Gifts & Bags",
        description: "Premium corporate gifts and promotional items for businesses",
        products: [
            {
                slug: "corporate-pens",
                name: "Corporate Pens",
                price: "Starting from $5",
                image: "/images/corporate-pens.png",
                rating: 4.8,
                reviews: 234,
                category: "Office Essentials",
            },
            {
                slug: "promotional-mugs",
                name: "Promotional Mugs",
                price: "Starting from $8",
                image: "/images/promotional-mugs.png",
                rating: 4.7,
                reviews: 187,
                category: "Drinkware",
            },
            {
                slug: "tote-bags",
                name: "Tote Bags",
                price: "Starting from $12",
                image: "/images/tote-bags.png",
                rating: 4.9,
                reviews: 156,
                category: "Bags",
            },
        ],
    },
}
